'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const scheduler = require('../scripts/spotify-album-artwork-scheduler'); const productionSafety = require('../scripts/spotify-artwork-backfill-production');
const FINGERPRINT = `sha256:${'a'.repeat(64)}`;
function authorizedEnv(){return{LIVEVAULT_ARTWORK_SCHEDULE_CONFIRM:scheduler.SCHEDULE_AUTHORIZATION,CF_WORKER_ENDPOINT:'https://worker.example.test',CF_WORKER_BROWSER_TOKEN:'synthetic-browser-token',SPOTIFY_CLIENT_ID:'synthetic-client-id',SPOTIFY_CLIENT_SECRET:'synthetic-client-secret'};}
async function immediateLease(options,operation){assert.equal(options.owner,scheduler.LEASE_OWNER);return operation({leaseId:'synthetic-lease'});}
test('DAB8 uses the agreed four-hour five-group five-second scheduled envelope',()=>{const o=scheduler.parseArgs(['--execute-scheduled']);assert.equal(o.intervalHours,4);assert.equal(o.cap,5);assert.equal(o.delayMs,5000);assert.equal(o.market,'SE');assert.equal(scheduler.MAX_TRACK_LOOKUPS_24H,30);});
test('DAB8 rejects faster cadence, larger cap, weaker pacing and alternate state path',()=>{assert.throws(()=>scheduler.parseArgs(['--execute-scheduled','--cap','6']),/between 1 and 5/);assert.throws(()=>scheduler.parseArgs(['--execute-scheduled','--delay-ms','4999']),/at least 5000/);assert.throws(()=>scheduler.parseArgs(['--execute-scheduled','--interval-hours','3']),/at least 4 hours/);assert.throws(()=>scheduler.parseArgs(['--execute-scheduled','--state','other.json']),/Unknown argument/);});
test('DAB8 due gate is exact at four hours',()=>{const s={schemaVersion:1,lastAttemptAt:'2026-08-13T06:00:00.000Z'};assert.equal(scheduler.scheduleDecision(s,{now:'2026-08-13T09:59:59.999Z'}).due,false);assert.equal(scheduler.scheduleDecision(s,{now:'2026-08-13T10:00:00.000Z'}).due,true);});
test('DAB8 rolling budget counts only reservations inside the preceding 24 hours',()=>{const s={schemaVersion:1,providerReservations:[{at:'2026-08-12T09:59:59.000Z',maxLookups:5},{at:'2026-08-12T10:00:01.000Z',maxLookups:5},{at:'2026-08-13T06:00:00.000Z',maxLookups:4}]};assert.equal(scheduler.remainingTrackBudget(s,'2026-08-13T10:00:00.000Z').remaining,21);});
test('DAB8 fails closed instead of discarding a future rolling-budget reservation',()=>{const s={schemaVersion:1,providerReservations:[{at:'2026-08-13T10:00:00.001Z',maxLookups:5}]};assert.throws(()=>scheduler.remainingTrackBudget(s,'2026-08-13T10:00:00.000Z'),/reservation is in the future/);});
test('DAB8 unchanged caught-up manifest skips lease, full history and Spotify',async()=>{let leases=0,runs=0;const states=[];const r=await scheduler.runScheduledCli({argv:['--execute-scheduled'],env:authorizedEnv(),now:()=> '2026-08-13T10:00:00.000Z',log:()=>{},readStateImpl:async()=>({schemaVersion:1,lastAttemptAt:'2026-08-13T06:00:00.000Z',lastPlanHadUnresolved:false,lastManifestFingerprint:FINGERPRINT,futureField:true}),writeStateImpl:async(_p,s)=>states.push(s),readManifestFingerprintImpl:async()=> FINGERPRINT,withLeaseImpl:async()=>{leases+=1;},runAlbumArtworkCliImpl:async()=>{runs+=1;}});assert.equal(r.status,'idle_unchanged');assert.equal(r.spotifyTrackLookups,0);assert.equal(r.fullHistoryRead,false);assert.equal(leases,0);assert.equal(runs,0);assert.equal(states[0].futureField,true);});
test('DAB8 fresh state performs zero work',async()=>{let runs=0,leases=0;const r=await scheduler.runScheduledCli({argv:['--execute-scheduled'],env:authorizedEnv(),now:()=> '2026-08-13T10:00:00.000Z',log:()=>{},readStateImpl:async()=>({schemaVersion:1,lastAttemptAt:'2026-08-13T09:00:00.000Z'}),writeStateImpl:async()=>{},withLeaseImpl:async()=>{leases+=1;},runAlbumArtworkCliImpl:async()=>{runs+=1;}});assert.equal(r.status,'not_due');assert.equal(r.nextDueAt,'2026-08-13T13:00:00.000Z');assert.equal(leases,0);assert.equal(runs,0);});
test('DAB8 busy provider lease defers without consuming the four-hour attempt',async()=>{let writes=0;const busy=new Error('busy');busy.code='SCHEDULER_LEASE_BUSY';const r=await scheduler.runScheduledCli({argv:['--execute-scheduled'],env:authorizedEnv(),now:()=> '2026-08-13T10:00:00.000Z',log:()=>{},readStateImpl:async()=>({schemaVersion:1}),writeStateImpl:async()=>{writes+=1;},withLeaseImpl:async()=>{throw busy;}});assert.equal(r.status,'deferred');assert.equal(r.reason,'scheduler_lease_busy');assert.equal(writes,0);});
test('DAB8 reserves rolling budget before provider work and reconciles to actual lookups',async()=>{const states=[];let invocation,clock=0;const r=await scheduler.runScheduledCli({argv:['--execute-scheduled','--market','us'],env:authorizedEnv(),now:()=> (++clock<3?'2026-08-13T10:00:00.000Z':'2026-08-13T10:02:00.000Z'),log:()=>{},readStateImpl:async()=>({schemaVersion:1,providerReservations:[{at:'2026-08-13T06:00:00.000Z',maxLookups:5}],futureField:true}),writeStateImpl:async(_p,s)=>states.push(JSON.parse(JSON.stringify(s))),withLeaseImpl:immediateLease,runAlbumArtworkCliImpl:async(o)=>{invocation=o;return{providerAlbumGroupsAttempted:2,providerAlbumGroupsRemaining:3,sourceManifestFingerprint:FINGERPRINT};}});assert.equal(r.status,'completed');assert.deepEqual(invocation.argv,['--execute','--write','--cap','5','--delay-ms','5000','--market','US']);assert.equal(invocation.env.LIVEVAULT_BACKFILL_CONFIRM,productionSafety.PRODUCTION_EXECUTION_CONFIRMATION);assert.equal(states[0].providerReservations.at(-1).maxLookups,5);assert.equal(states[1].providerReservations.at(-1).maxLookups,2);assert.equal(states[1].lastPlanHadUnresolved,true);});
test('DAB8 refuses a seventh five-lookup reservation inside a rolling day',async()=>{const reservations=['2026-08-12T10:00:01.000Z','2026-08-12T14:00:00.000Z','2026-08-12T18:00:00.000Z','2026-08-12T22:00:00.000Z','2026-08-13T02:00:00.000Z','2026-08-13T06:00:00.000Z'].map(at=>({at,maxLookups:5}));let runs=0;const r=await scheduler.runScheduledCli({argv:['--execute-scheduled'],env:authorizedEnv(),now:()=> '2026-08-13T10:00:00.000Z',log:()=>{},readStateImpl:async()=>({schemaVersion:1,providerReservations:reservations}),writeStateImpl:async()=>{},withLeaseImpl:immediateLease,runAlbumArtworkCliImpl:async()=>{runs+=1;}});assert.equal(r.status,'deferred');assert.equal(r.reason,'rolling_24h_track_lookup_budget');assert.equal(runs,0);});
test('DAB8 rechecks the due marker after acquiring the provider lease',async()=>{let reads=0,runs=0,writes=0;const r=await scheduler.runScheduledCli({argv:['--execute-scheduled'],env:authorizedEnv(),now:()=> '2026-08-13T10:00:00.000Z',log:()=>{},readStateImpl:async()=>{reads+=1;return reads===1?{schemaVersion:1}:{schemaVersion:1,lastAttemptAt:'2026-08-13T09:00:00.000Z'};},writeStateImpl:async()=>{writes+=1;},withLeaseImpl:immediateLease,runAlbumArtworkCliImpl:async()=>{runs+=1;}});assert.equal(r.status,'not_due');assert.equal(runs,0);assert.equal(writes,0);});
test('DAB8 does not mark a failed manifest check as a completed maintenance wake',async()=>{let writes=0,leases=0;await assert.rejects(()=>scheduler.runScheduledCli({argv:['--execute-scheduled'],env:authorizedEnv(),now:()=> '2026-08-13T10:00:00.000Z',log:()=>{},readStateImpl:async()=>({schemaVersion:1,lastAttemptAt:'2026-08-13T06:00:00.000Z',lastPlanHadUnresolved:false,lastManifestFingerprint:FINGERPRINT}),writeStateImpl:async()=>{writes+=1;},readManifestFingerprintImpl:async()=>{throw new Error('synthetic manifest failure');},withLeaseImpl:async()=>{leases+=1;}}),/synthetic manifest failure/);assert.equal(writes,0);assert.equal(leases,0);});
test('DAB8 keeps its full reservation when the child completion summary is malformed',async()=>{const states=[];await assert.rejects(()=>scheduler.runScheduledCli({argv:['--execute-scheduled'],env:authorizedEnv(),now:()=> '2026-08-13T10:00:00.000Z',log:()=>{},readStateImpl:async()=>({schemaVersion:1}),writeStateImpl:async(_p,s)=>states.push(JSON.parse(JSON.stringify(s))),withLeaseImpl:immediateLease,runAlbumArtworkCliImpl:async()=>({providerAlbumGroupsAttempted:'2',providerAlbumGroupsRemaining:0,sourceManifestFingerprint:FINGERPRINT})}),/invalid attempted-track count/);assert.equal(states.length,2);assert.equal(states[0].providerReservations[0].maxLookups,5);assert.equal(states[1].providerReservations[0].maxLookups,5);assert.equal(states[1].lastOutcome,'failed');});
test('DAB8 requires a valid fingerprint before entering caught-up maintenance mode',async()=>{const states=[];await assert.rejects(()=>scheduler.runScheduledCli({argv:['--execute-scheduled'],env:authorizedEnv(),now:()=> '2026-08-13T10:00:00.000Z',log:()=>{},readStateImpl:async()=>({schemaVersion:1}),writeStateImpl:async(_p,s)=>states.push(JSON.parse(JSON.stringify(s))),withLeaseImpl:immediateLease,runAlbumArtworkCliImpl:async()=>({providerAlbumGroupsAttempted:0,providerAlbumGroupsRemaining:0,sourceManifestFingerprint:null})}),/without a valid source-manifest fingerprint/);assert.equal(states.at(-1).lastOutcome,'failed');assert.equal(states.at(-1).providerReservations[0].maxLookups,5);});
