'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const links=require('../scripts/lib/nonPlaylistTrackLinks');const artwork=require('../scripts/lib/providerNeutralArtworkV136');const diagnostics=require('../scripts/lib/spotifyDiagnosticsV135');const history=require('../listeningHistoryV2');const albumArtwork=require('../spotifyListeningAlbumArtworkV113');const mbLinks=require('../scripts/lib/musicbrainzTrackLinksV137');

test('v137 reuses concert and prediction evidence without provider I/O',()=>{const bands=[{id:'band-a',name:'Example Artist',musicbrainz:{spotify:{status:'confirmed',id:'artist123'}}}],concerts=[{bandId:'band-a',bandName:'Example Artist',setlist:{songs:[{name:'Known Song',spotifyUrl:'https://open.spotify.com/track/track123'}]},predictedSetlist:{songs:[{name:'Predicted Song',spotifyTrackId:'track456'}]}}],resolver=links.createResolver(links.collectConcertEvidence(concerts,bands));assert.equal(resolver.resolve({spotifyArtistId:'artist123',recordingTitle:'Known Song'}),'https://open.spotify.com/track/track123');assert.equal(resolver.resolve({spotifyArtistId:'artist123',recordingTitle:'Predicted Song'}),'https://open.spotify.com/track/track456');assert.equal(resolver.resolve({artistName:'Example Artist',recordingTitle:'Known Song'}),'https://open.spotify.com/track/track123');});

test('v137 duplicate artist names never create a name-key reuse alias',()=>{const bands=[{id:'band-a',name:'Same Name'},{id:'band-b',name:'Same Name'}],concerts=[{bandId:'band-a',bandName:'Same Name',setlist:{songs:[{name:'Song',spotifyTrackId:'one'}]}},{bandId:'band-b',bandName:'Same Name',setlist:{songs:[{name:'Song',spotifyTrackId:'two'}]}}],resolver=links.createResolver(links.collectConcertEvidence(concerts,bands));assert.equal(resolver.resolve({artistName:'Same Name',recordingTitle:'Song'}),null);assert.equal(resolver.resolve({bandId:'band-a',recordingTitle:'Song'}),'https://open.spotify.com/track/one');assert.equal(resolver.resolve({bandId:'band-b',recordingTitle:'Song'}),'https://open.spotify.com/track/two');});

test('v137 ambiguous non-playlist evidence fails closed',()=>{const resolver=links.createResolver([{bandId:'band-a',recordingTitle:'Song',spotifyTrackId:'one'},{bandId:'band-a',recordingTitle:'Song',spotifyTrackId:'two'}]);assert.equal(resolver.resolve({bandId:'band-a',recordingTitle:'Song'}),null);assert.equal(resolver.hasConflict({bandId:'band-a',recordingTitle:'Song'}),true);});

test('v137 private callers can reuse retained ListenBrainz relations without widening automation access',()=>{const bands=[{id:'band-a',name:'Example Artist'}];const events=[{localBandId:'band-a',artistCreditName:'Example Artist',recordingTitle:'ListenBrainz Song',listenbrainzUrlRels:['https://open.spotify.com/track/lb123']}];const resolver=links.createResolver(links.collectListeningEvidence(events,{bands}));assert.equal(resolver.resolve({bandId:'band-a',recordingTitle:'ListenBrainz Song'}),'https://open.spotify.com/track/lb123');assert.equal(resolver.resolve({artistName:'Example Artist',recordingTitle:'ListenBrainz Song'}),'https://open.spotify.com/track/lb123');});

test('v137 scheduled lookup passes exact recording MBID into MusicBrainz before title fallback',()=>{const preload=fs.readFileSync(path.join(__dirname,'..','scripts','preloadStructuredRun.js'),'utf8');assert.match(preload,/recordingMbid: uniqueRecordingMbid\(artistName, recordingTitle\)/);assert.match(preload,/safeConcertEvidence = nonPlaylist\.collectConcertEvidence/);});

test('v137 CAA suppression requires explicit ListenBrainz CAA evidence',()=>{const mbid='12345678-1234-4123-8123-123456789abc';assert.equal(artwork.artworkEvidence({musicbrainzReleaseId:mbid}),null);assert.ok(artwork.artworkEvidence({musicbrainzReleaseId:mbid,listenbrainzCaaReleaseMbid:mbid,listenbrainzCaaId:'12345'}));const bare=history.sanitizeEvent({stableListenId:'listen-1',listenedAt:'2026-08-17T00:00:00Z',listenedDurationMs:180000,artistCreditName:'Example Artist',recordingTitle:'Song',releaseTitle:'Album',spotifyTrackId:'track123',musicbrainzReleaseId:mbid,source:'spotify_import'});assert.equal(bare.albumArtworkUrl,undefined);global.bands=[{id:'band-a',name:'Example Artist'}];global.listeningEvents=[{...bare,localBandId:'band-a'}];assert.deepEqual(albumArtwork.albumOrientedUnresolvedTrackIds({records:{}},global.listeningEvents),['track123']);delete global.bands;delete global.listeningEvents;});

test('v137 explicit CAA evidence can satisfy artwork before Spotify',()=>{const mbid='12345678-1234-4123-8123-123456789abc',event=history.sanitizeEvent({stableListenId:'listen-2',listenedAt:'2026-08-17T00:00:01Z',listenedDurationMs:180000,artistCreditName:'Example Artist',recordingTitle:'Song',releaseTitle:'Album',spotifyTrackId:'track123',musicbrainzReleaseId:mbid,listenbrainzCaaReleaseMbid:mbid,listenbrainzCaaId:'cover1',source:'spotify_import'});assert.equal(event.albumArtworkUrl,`https://coverartarchive.org/release/${mbid}/front-500`);});

test('v137 diagnostics count attempted operations',()=>{const usage={state:{spotify:{callsThisRun:0,circuit:null}}};diagnostics.resetDiagnostics(usage);const before=diagnostics.calls(usage);usage.state.spotify.callsThisRun=1;diagnostics.recordOperation(usage,{lane:'album_artwork',endpoint:'track_exact',before,result:{kind:'ok'}});assert.equal(usage.state.spotify.diagnostics.outcomes.attempted,1);assert.equal(usage.state.spotify.diagnostics.callsByLane.album_artwork,1);});

test('v137 MusicBrainz relation extraction is exact and fail-closed',()=>{assert.equal(mbLinks.spotifyUrlFromRelations([{url:{resource:'https://open.spotify.com/track/abc123'}}]),'https://open.spotify.com/track/abc123');assert.equal(mbLinks.spotifyUrlFromRelations([{url:{resource:'https://open.spotify.com/track/a'}},{url:{resource:'https://open.spotify.com/track/b'}}]),null);});
