'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const lifecycle = require('../scripts/lib/releaseLifecycle');
const now = '2027-07-16T12:00:00.000Z';
const album = (extra = {}) => ({ title: 'Synthetic Record', type: 'Album', musicbrainzReleaseGroupMbid: 'qa-release', releaseDate: '2027-07-23', ...extra });

test('exports the four lifecycle stages', () => assert.deepEqual(Object.values(lifecycle.STAGES).sort(), ['album_announced', 'new_single', 'out_today', 'upcoming_release']));
test('canonical release and alert IDs are deterministic', () => { const release = album(); assert.equal(lifecycle.canonicalReleaseId(release), lifecycle.canonicalReleaseId(release)); assert.equal(lifecycle.lifecycleAlertId('qa-band', release, lifecycle.STAGES.ALBUM_ANNOUNCED), lifecycle.lifecycleAlertId('qa-band', release, lifecycle.STAGES.ALBUM_ANNOUNCED)); });
test('lifecycle IDs differ by band, release type and stage', () => { const release = album(); const id = lifecycle.lifecycleAlertId('a', release, lifecycle.STAGES.ALBUM_ANNOUNCED); assert.notEqual(id, lifecycle.lifecycleAlertId('b', release, lifecycle.STAGES.ALBUM_ANNOUNCED)); assert.notEqual(id, lifecycle.lifecycleAlertId('a', { ...release, type: 'EP', musicbrainzReleaseGroupMbid: null }, lifecycle.STAGES.ALBUM_ANNOUNCED)); assert.notEqual(id, lifecycle.lifecycleAlertId('a', release, lifecycle.STAGES.OUT_TODAY)); });
test('excluded variants are silent', () => { for (const title of ['Record (Deluxe Edition)', 'Record Remastered', 'Record Reissue', 'Record Compilation']) assert.deepEqual(lifecycle.eligibleStages(album({ title }), now), []); });
test('albums and EPs announce while trusted Spotify singles create only new-single', () => { assert.ok(lifecycle.eligibleStages(album(), now).includes(lifecycle.STAGES.ALBUM_ANNOUNCED)); assert.ok(lifecycle.eligibleStages(album({ type: 'EP' }), now).includes(lifecycle.STAGES.ALBUM_ANNOUNCED)); assert.deepEqual(lifecycle.eligibleStages(album({ type: 'Single', spotifyReleaseId: 'qa-single', spotifyUrl: 'https://open.spotify.com/album/qa-single' }), now), [lifecycle.STAGES.NEW_SINGLE]); });
test('upcoming stage is exactly seven days before album or EP and never a single', () => { assert.ok(lifecycle.eligibleStages(album(), now).includes(lifecycle.STAGES.UPCOMING_RELEASE)); assert.equal(lifecycle.eligibleStages(album({ releaseDate: '2027-07-22' }), now).includes(lifecycle.STAGES.UPCOMING_RELEASE), false); assert.equal(lifecycle.eligibleStages(album({ releaseDate: '2027-07-24' }), now).includes(lifecycle.STAGES.UPCOMING_RELEASE), false); assert.equal(lifecycle.eligibleStages(album({ type: 'Single', spotifyReleaseId: 's' }), now).includes(lifecycle.STAGES.UPCOMING_RELEASE), false); });
test('recent announcement suppresses upcoming and release day emits out today', () => { assert.equal(lifecycle.eligibleStages(album(), now, { album_announcedAt: '2027-07-10T00:00:00.000Z' }).includes(lifecycle.STAGES.UPCOMING_RELEASE), false); assert.ok(lifecycle.eligibleStages(album({ releaseDate: '2027-07-16' }), now).includes(lifecycle.STAGES.OUT_TODAY)); });
test('partial dates do not qualify for date-based stages', () => { assert.equal(lifecycle.eligibleStages(album({ releaseDate: '2027-07' }), now).includes(lifecycle.STAGES.UPCOMING_RELEASE), false); assert.equal(lifecycle.eligibleStages(album({ releaseDate: '2027' }), now).includes(lifecycle.STAGES.OUT_TODAY), false); });
