'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const vm = require('node:vm'); const path = require('node:path'); const { webcrypto } = require('node:crypto');
function harness() { const values = {}; const location = { origin: 'https://mstpln.github.io', pathname: '/concert-tracker-mobile/', search: '', assign(url) { this.assigned = url; } }; const chrome = { storage: { local: { async get(keys) { if (Array.isArray(keys)) return Object.fromEntries(keys.map((key) => [key, values[key]])); return { [keys]: values[keys] }; }, async set(next) { Object.assign(values, next); }, async remove(keys) { for (const key of Array.isArray(keys) ? keys : [keys]) delete values[key]; } } } }; const sandbox = { window: { chrome }, chrome, location, history: { replaceState() {} }, crypto: webcrypto, TextEncoder, URL, URLSearchParams, btoa: (value) => Buffer.from(value, 'binary').toString('base64'), setTimeout, Date, Uint8Array, Error, fetch: async () => { throw new Error('unexpected'); } }; vm.runInNewContext(fs.readFileSync(path.join(__dirname, '..', 'spotifyUser.js'), 'utf8'), sandbox); return { api: sandbox.window.SpotifyUser, values, location }; }
test('1-17 manual and generated playlist fields remain separate in the UI contract', () => { const app = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8'); assert.match(app, /playlistUrl/); assert.match(app, /predictedPlaylist/); assert.match(app, /Manual linked · Predicted mix saved/); assert.match(app, /\['playlist', 'spotify', 'Playlist'/); assert.doesNotMatch(app, /\['playlist', 'music', 'Playlist'/); assert.match(app, /Spotify public Client ID/); assert.doesNotMatch(app, /Client Secret.*input/); });
test('18-31 PKCE uses random state/verifier, SHA-256 challenge, callback validation, token exchange and rotated refresh', async () => { const { api, values, location } = harness(); const one = api.random(); const two = api.random(); assert.notEqual(one, two); assert.notEqual(await api.challengeFor(one), one); await api.beginAuthorization('public-client'); assert.match(location.assigned, /code_challenge_method=S256/); assert.match(location.assigned, /playlist-modify-private/); const pending = values.spotifyUserPkcePending; location.search = `?code=code&state=${pending.state}`; const result = await api.handleCallback(async () => ({ ok: true, json: async () => ({ access_token: 'access', refresh_token: 'refresh', expires_in: 3600, token_type: 'Bearer' }) })); assert.equal(result.kind, 'ok'); assert.equal(values.spotifyUserAuthorization.clientId, 'public-client'); values.spotifyUserAuthorization.expiresAt = new Date(0).toISOString(); const calls = []; const refreshed = await api.refresh(values.spotifyUserAuthorization, async (_url, opts) => { calls.push(String(opts.body)); return { ok: true, json: async () => ({ access_token: 'new', refresh_token: 'rotated', expires_in: 3600 }) }; }); assert.equal(refreshed.refreshToken, 'rotated'); assert.match(calls[0], /grant_type=refresh_token/); location.search = '?state=missing-code'; assert.equal((await api.handleCallback()).kind, 'error'); await api.clearAuth(); assert.equal(values.spotifyUserAuthorization, undefined); });
test('32-71 review and playlist creation use private current-user endpoints, ordered chunks, and no update endpoint', async () => { const { api, values } = harness(); values.spotifyUserAuthorization = { clientId: 'id', accessToken: 'token', refreshToken: 'refresh', expiresAt: new Date(Date.now() + 3600000).toISOString(), scope: api.SCOPE, tokenType: 'Bearer' }; const requests = []; const fetcher = async (url, opts) => { requests.push([url, opts]); if (url.endsWith('/me/playlists')) return { ok: true, json: async () => ({ id: 'playlist', external_urls: { spotify: 'https://open.spotify.com/playlist/playlist' } }) }; return { ok: true, json: async () => ({ snapshot_id: 's' }) }; }; const uris = Array.from({ length: 101 }, (_, i) => `spotify:track:${i}`); const result = await api.createPrivatePlaylist('Name', uris, fetcher); assert.equal(result.added, 101); assert.equal(requests.length, 3); assert.match(requests[0][0], /\/me\/playlists$/); assert.match(requests[1][0], /\/playlists\/playlist\/items$/); assert.equal(JSON.parse(requests[0][1].body).public, false); assert.deepEqual(JSON.parse(requests[1][1].body).uris.slice(0, 2), uris.slice(0, 2)); const resumed = await api.createPrivatePlaylist('Name', uris, fetcher, { playlist: result.playlist, added: result.added }); assert.equal(resumed.added, 101); assert.equal(requests.length, 3); const source = fs.readFileSync(path.join(__dirname, '..', 'spotifyUser.js'), 'utf8'); assert.doesNotMatch(source, /PUT.*playlists/); assert.doesNotMatch(source, /\/tracks/); });
test('72-88 regression contract preserves weather, prediction, checklist, native track checkboxes and no R2 token fields', () => { const app = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8'); const source = fs.readFileSync(path.join(__dirname, '..', 'spotifyUser.js'), 'utf8'); assert.match(app, /weatherRowStatus/); assert.match(app, /Predicted setlist/); assert.match(app, /Checklist/); assert.match(app, /type="checkbox" class="predicted-track-check"/); assert.match(app, /predictedMixReviewItems/); assert.match(app, /Cover excluded/); assert.match(app, /playlistOperations/); assert.match(source, /chrome\.storage\.local/); assert.doesNotMatch(source, /dlWriteJsonFile|concerts\.json|client_secret/i); });
test('playlist creation resumes an interrupted add-tracks operation without creating a duplicate playlist', async () => {
  const { api, values } = harness();
  values.spotifyUserAuthorization = { clientId: 'id', accessToken: 'token', refreshToken: 'refresh', expiresAt: new Date(Date.now() + 3600000).toISOString(), scope: api.SCOPE, tokenType: 'Bearer' };
  const requests = []; let failItems = true;
  const fetcher = async (url, opts) => { requests.push(url); if (url.endsWith('/me/playlists')) return { ok: true, json: async () => ({ id: 'playlist', external_urls: { spotify: 'https://open.spotify.com/playlist/playlist' } }) }; if (failItems) return { ok: false, status: 500, headers: { get() { return null; } } }; return { ok: true, json: async () => ({ snapshot_id: 'saved' }) }; };
  const uris = ['spotify:track:one', 'spotify:track:two']; let operation;
  await assert.rejects(() => api.createPrivatePlaylist('Name', uris, fetcher), (error) => { operation = error.operation; return true; });
  assert.equal(operation.playlist.id, 'playlist'); assert.equal(operation.added, 0); assert.equal(requests.filter((url) => url.endsWith('/me/playlists')).length, 1);
  failItems = false; const resumed = await api.createPrivatePlaylist('Name', uris, fetcher, operation);
  assert.equal(resumed.added, 2); assert.equal(requests.filter((url) => url.endsWith('/me/playlists')).length, 1);
});
test('playlist review UI has one shared primary creation treatment and keeps its playlist panel open across refreshes', () => {
  const app = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8'); const css = fs.readFileSync(path.join(__dirname, '..', 'app.css'), 'utf8');
  assert.match(app, /const prepOpenPanels = new Map\(\)/); assert.match(app, /prepOpenPanels\.set\(c\.id, 'playlist'\)/); assert.match(app, /const openPanel = prepOpenPanels\.get\(c\.id\) \|\| ''/);
  assert.match(app, /class="btn-primary playlist-save-btn"/); assert.match(app, /class="btn-primary playlist-review-open"/); assert.match(app, /class="btn-primary playlist-create-confirm"/);
  assert.match(app, /Review & create/); assert.doesNotMatch(app, /Create playlist from matched songs/); assert.match(app, /Create a playlist from the Playlist section\./);
  assert.match(css, /\.playlist-review-actions \{ display: flex; flex-wrap: wrap;/); assert.doesNotMatch(css, /playlist-review-open\s*\{[^}]*background:/);
});
test('playlist creation reports missing Spotify authorization before making a playlist request', async () => {
  const { api } = harness();
  await assert.rejects(() => api.createPrivatePlaylist('Name', ['spotify:track:one']), /Connect Spotify first/);
  const app = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8'); assert.match(app, /Spotify is not connected\. Connect Spotify in Settings\./); assert.match(app, /await SpotifyUser\.getAuth\(\)/);
});
