'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
function weatherHarness() {
  const store = {}; const window = { chrome: { storage: { local: { async get(key) { return { [key]: store[key] }; }, async set(values) { Object.assign(store, values); } } } } };
  vm.runInNewContext(fs.readFileSync(path.join(__dirname, '..', 'weather.js'), 'utf8'), { window, chrome: window.chrome, Intl, Date, Number, String, Math, URL, fetch: async () => { throw new Error('unexpected'); }, console });
  return { api: window.ConcertWeather, store };
}
const now = new Date('2026-07-16T12:00:00Z');
const concert = (extra = {}) => ({ id: 'c1', date: '2026-07-26', time: '19:00', attending: true, city: 'Copenhagen', country: 'Denmark', ...extra });
const hourly = { timezone: 'Europe/Copenhagen', hourly: { time: ['2026-07-26T17:00', '2026-07-26T19:00', '2026-07-26T21:00', '2026-07-26T23:00'], temperature_2m: [17.2, 18.4, 16.8, 14], apparent_temperature: [17, 18, 16, 13], precipitation_probability: [10, 25, 40, 30], weather_code: [1, 2, 61, 3], wind_speed_10m: [12.2, 15.7, 20.4, 18] } };
test('1-7 venue-local ten-day boundary allows today through ten days and blocks eleven days', () => { const { api } = weatherHarness(); assert.equal(api.availability(concert({ date: '2026-07-27' }), 'Europe/Copenhagen', now).available, false); assert.equal(api.availability(concert(), 'Europe/Copenhagen', now).available, true); assert.equal(api.availability(concert({ date: '2026-07-25' }), 'Europe/Copenhagen', now).available, true); assert.equal(api.availability(concert({ date: '2026-07-16' }), 'Europe/Copenhagen', now).available, true); });
test('8-15 direct coordinates win, safe city-country geocoding is cached, and wrong country is rejected', async () => { const { api, store } = weatherHarness(); assert.equal(JSON.stringify(await api.resolveLocation(concert({ latitude: 55.6, longitude: 12.5 }))), JSON.stringify({ kind: 'ok', latitude: 55.6, longitude: 12.5, timezone: null })); let calls = 0; const fetcher = async () => { calls++; return { ok: true, json: async () => ({ results: [{ name: 'Copenhagen', country: 'Denmark', latitude: 55.7, longitude: 12.6, timezone: 'Europe/Copenhagen' }] }) }; }; const found = await api.resolveLocation(concert(), fetcher); assert.equal(found.kind, 'ok'); await api.resolveLocation(concert(), fetcher); assert.equal(calls, 1); const bad = await api.resolveLocation(concert({ id: 'c2', country: 'Sweden' }), fetcher); assert.equal(bad.kind, 'unavailable'); assert.ok(Object.keys(store).every((key) => key.startsWith('weather:'))); });
test('16-29 timezone hourly window, WMO mapping, rounding, and malformed data are normalized safely', () => { const { api } = weatherHarness(); assert.equal(JSON.stringify(api.desiredHours(concert())), '[17,19,21,23]'); assert.equal(JSON.stringify(api.desiredHours(concert({ time: null }))), '[17,19,21,23]'); const forecast = api.normalizeForecast(hourly, concert(), { latitude: 1, longitude: 2 }, now); assert.equal(forecast.timezone, 'Europe/Copenhagen'); assert.equal(forecast.hours.length, 4); assert.equal(forecast.hours[1].temperatureC, 18); assert.equal(forecast.hours[1].conditionKey, 'partlyCloudyDay'); assert.equal(Math.max(...forecast.hours.map((hour) => hour.precipitationProbability)), 40); assert.equal(api.normalizeForecast({}, concert(), { latitude: 1, longitude: 2 }, now), null); assert.equal(api.condition(95, '2026-07-26T19:00').text, 'Thunderstorms'); });
test('30-44 normalized cache avoids fetching, expires safely, preserves stale fallback and deduplicates in-flight requests', async () => { const { api, store } = weatherHarness(); const c = concert({ latitude: 55.6, longitude: 12.5 }); const key = api.storageKey(c, { latitude: 55.6, longitude: 12.5 }); store[key] = { concertId: 'c1', concertDate: c.date, fetchedAt: now.toISOString(), expiresAt: new Date(now.getTime() + 3600000).toISOString(), latitude: 55.6, longitude: 12.5, timezone: 'Europe/Copenhagen', provider: 'open-meteo', hours: [{ time: '2026-07-26T19:00', temperatureC: 18, apparentTemperatureC: 18, precipitationProbability: 25, windSpeedKmh: 16, weatherCode: 2, conditionKey: 'partlyCloudyDay', conditionText: 'Partly cloudy' }] }; let calls = 0; const fetcher = async () => { calls++; return { ok: true, json: async () => hourly }; }; const cached = await api.load(c, { fetchImpl: fetcher, now }); assert.equal(cached.cached, true); assert.equal(calls, 0); store[key].expiresAt = new Date(now.getTime() - 1).toISOString(); const [one, two] = await Promise.all([api.load(c, { fetchImpl: fetcher, now }), api.load(c, { fetchImpl: fetcher, now })]); assert.equal(one.kind, 'ok'); assert.equal(two.kind, 'ok'); assert.equal(calls, 1); assert.equal(JSON.stringify(store[key]).includes('hourly'), false); });
test('45-66 existing UI keeps the preparation row contract and uses local SVG weather icons', () => { const app = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8'); const icons = fs.readFileSync(path.join(__dirname, '..', 'icons.js'), 'utf8'); assert.match(app, /Available 10 days before the concert/); assert.match(app, /Loading forecast/); assert.match(app, /Weather unavailable for this venue/); assert.match(app, /Forecast temporarily unavailable/); assert.match(app, /weather-retry/); assert.match(app, /weatherSummary/); assert.match(app, /concertPrepGroupHtml/); assert.match(app, /isPast \? mcLinksRowHtml\(c, true\) : concertPrepGroupHtml\(c\)/); assert.match(icons, /weatherClearDay/); assert.match(icons, /weatherThunderstorm/); assert.doesNotMatch(app, /navigator\.geolocation/); });
