'use strict';
(function attachGau2Settings(root, factory) {
  const api = factory(root);
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.BandmarkrGau2SettingsV118 = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, (root) => {
  const AUTOMATION_GROUPS = Object.freeze([
    ['Concert Updates', 'Finds new concerts and updates known concert information.'],
    ['Web Concert Search', 'Looks for concerts that structured providers may have missed a show.'],
    ['Listening Updates', 'Keeps listening history up to date.'],
    ['Artist Updates', 'Fills in and refreshes artist identity and metadata.'],
    ['Artist Images', 'Fills in missing artist artwork.'],
    ['Setlist Updates', 'Finds and refreshes setlists and related setlist data.'],
  ]);
  const PROVIDER_PURPOSES = Object.freeze({ ticketmaster:'Concert discovery, event information, venue information and trusted attraction identity.', tavily:'Targeted web concert research when structured providers may have missed a show.', groq:'Structured extraction and selected artist-enrichment tasks.', setlistfm:'Actual setlists, setlist history and setlist-derived context.', spotify:'Artist identity, releases, track links, metadata and artwork.', musicbrainz:'Artist identity, artist metadata and release/catalogue structure.', listenbrainz:'Listening-history ingestion and synchronization.' });
  const esc = (value) => String(value == null ? '' : value).replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
  const finite = (value) => value !== null && value !== undefined && value !== '' && Number.isFinite(Number(value));
  const count = (value) => Math.max(0, finite(value) ? Number(value) : 0);
  function formatMusicbrainzConfidence(value) { return finite(value) ? `${Math.max(0, Math.min(100, Math.round(Number(value))))}/100` : 'Confidence unavailable'; }
  function repairMusicbrainzConfidenceHtml(html) { return String(html || '').replace(/(?:undefined|null|NaN)\/100/g, 'Confidence unavailable'); }
  function statusFromRun(run) {
    if (!run) return { label:'Warning', kind:'warning', problem:'No recent status is available.' };
    const value = String(run.status || '').trim().toLowerCase();
    if (['error','failed','failure'].includes(value) || run.error) return { label:'Failed', kind:'failed', problem:String(run.error || 'The latest run failed.') };
    if (['ok','success','successful','complete','completed'].includes(value)) return { label:'Healthy', kind:'healthy', problem:'' };
    return { label:'Warning', kind:'warning', problem:value ? `Latest status: ${value}.` : 'The latest outcome is not reported.' };
  }
  function listenBrainzAutomationState(connection) {
    if (!connection) return { label:'Warning', kind:'warning', problem:'ListenBrainz is not connected on this device.' };
    if (!Number.isFinite(Date.parse(connection.lastSyncAt || ''))) return { label:'Warning', kind:'warning', problem:'ListenBrainz is configured, but no successful sync is recorded yet.' };
    return { label:'Healthy', kind:'healthy', problem:'' };
  }
  function dateTime(value) { const parsed=Date.parse(value||''); return Number.isFinite(parsed) ? new Intl.DateTimeFormat('en',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(parsed)) : 'Not available'; }
  function nextMwfUtc(now=new Date()) { for(let offset=0;offset<8;offset+=1){ const c=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+offset,1)); if([1,3,5].includes(c.getUTCDay())&&c>now)return c.toISOString(); } return null; }
  function nextFocusedWebUtc(now=new Date()) { return [new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1,2)),new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),15,2)),new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1,2))].filter((d)=>d>now).sort((a,b)=>a-b)[0]?.toISOString()||null; }
  function usageState(){try{return typeof apiUsage==='undefined'?null:apiUsage;}catch(_){return null;}}
  function bandState(){try{return Array.isArray(bands)?bands:[];}catch(_){return[];}}
  function concertState(){try{return Array.isArray(concerts)?concerts:[];}catch(_){return[];}}
  function listeningState(){try{return Array.isArray(listeningEvents)?listeningEvents:[];}catch(_){return[];}}
  function listenBrainzConnection(){try{return root.LiveVaultListenBrainz?.connection?.()||null;}catch(_){return null;}}
  function latestRunByMode(usage,mode){const explicit=usage?.automationRuns?.[mode];if(explicit)return explicit;const last=usage?.lastRun;if(!last)return null;if(mode==='focusedTavilyConcert')return last.mode==='tavily-concert-only'?last:null;if(mode==='structuredResearch')return last.mode!=='tavily-concert-only'?last:null;return null;}
  function latestRun(...runs){return runs.filter(Boolean).sort((a,b)=>(Date.parse(b.finishedAt||b.startedAt||'')||0)-(Date.parse(a.finishedAt||a.startedAt||'')||0))[0]||null;}
  function resultFor(run,a,b,c,d,fallback){if(!run)return fallback;const p=[];if(finite(run[a]))p.push(`${count(run[a]).toLocaleString()} ${b}`);if(finite(run[c]))p.push(`${count(run[c]).toLocaleString()} ${d}`);return p.join(' · ')||'A run is recorded, but no outcome counts are reported.';}
  function automationRows(now=new Date()){
    const usage=usageState()||{},structured=latestRunByMode(usage,'structuredResearch'),focused=latestRunByMode(usage,'focusedTavilyConcert'),artistRun=latestRun(usage.lastProviderIdentityRun,usage.lastMusicbrainzRun),lb=listenBrainzConnection();
    const ss=statusFromRun(structured),fs=statusFromRun(focused),as=statusFromRun(artistRun),ls=listenBrainzAutomationState(lb),validSync=ls.kind==='healthy'?lb.lastSyncAt:null;
    return [
      {name:AUTOMATION_GROUPS[0][0],description:AUTOMATION_GROUPS[0][1],...ss,lastSuccess:ss.kind==='healthy'?structured?.finishedAt:null,nextExpected:nextMwfUtc(now),result:resultFor(structured,'bandsProcessed','bands checked','concertsAdded','concerts found','No separate recent result is reported.')},
      {name:AUTOMATION_GROUPS[1][0],description:AUTOMATION_GROUPS[1][1],...fs,lastSuccess:fs.kind==='healthy'?focused?.finishedAt:null,nextExpected:nextFocusedWebUtc(now),result:resultFor(focused,'bandsAttempted','artists checked','concertsAdded','concerts found','No separate recent result is reported.')},
      {name:AUTOMATION_GROUPS[2][0],description:AUTOMATION_GROUPS[2][1],...ls,lastSuccess:validSync,nextExpected:validSync?new Date(Date.parse(validSync)+21600000).toISOString():null,result:validSync?`Listening history synced through ${dateTime(validSync)}`:'No successful device sync is currently recorded.'},
      {name:AUTOMATION_GROUPS[3][0],description:AUTOMATION_GROUPS[3][1],...as,lastSuccess:as.kind==='healthy'?artistRun?.finishedAt:null,nextExpected:null,result:resultFor(artistRun,'identityUpdates','identities updated','spotifyCalls','Spotify checks','No recent artist-update result is reported.')},
      {name:AUTOMATION_GROUPS[4][0],description:AUTOMATION_GROUPS[4][1],label:'Warning',kind:'warning',problem:'Trusted-local artwork scheduler status is not reported to this device.',lastSuccess:null,nextExpected:null,result:'Artwork scheduler state is not reported to this device.'},
      {name:AUTOMATION_GROUPS[5][0],description:AUTOMATION_GROUPS[5][1],...ss,lastSuccess:ss.kind==='healthy'?structured?.finishedAt:null,nextExpected:nextMwfUtc(now),result:structured&&finite(structured.setlistsAdded)?`${count(structured.setlistsAdded).toLocaleString()} setlists updated`:'No separate recent setlist result is reported.'},
    ];
  }
  function automationRowHtml(row){return `<article class="gau2-automation-row"><div class="gau2-automation-heading"><strong>${esc(row.name)}</strong><span class="gau2-status is-${esc(row.kind)}">${esc(row.label)}</span></div><p class="settings-hint gau2-automation-description">${esc(row.description)}</p><div class="gau2-automation-meta"><span><b>Last successful run</b>${esc(row.lastSuccess?dateTime(row.lastSuccess):'Not available')}</span><span><b>Next expected run</b>${esc(row.nextExpected?dateTime(row.nextExpected):'Not reported')}</span><span><b>Last result</b>${esc(row.result)}</span></div>${row.problem?`<p class="gau2-problem is-${esc(row.kind)}">${esc(row.problem)}</p>`:''}</article>`;}
  function providerDetailsHtml(id,headline,detail){return `<div class="gau2-provider-details"><p><strong>${esc(headline)}</strong></p><p class="settings-hint">${esc(detail)}</p><p class="settings-hint"><strong>Used for:</strong> ${esc(PROVIDER_PURPOSES[id])}</p></div>`;}
  function supplementalProvidersHtml(){
    const usage=usageState(),spotify=usage?.spotify,mb=usage?.musicbrainz,lb=listenBrainzConnection(),validLbSync=Number.isFinite(Date.parse(lb?.lastSyncAt||''));
    const spotifySummary=spotify&&finite(spotify.callsToday)?`${count(spotify.callsToday).toLocaleString()} calls today${finite(spotify.dailyCap)?` · BANDMARKR cap ${count(spotify.dailyCap).toLocaleString()}/day`:''}`:'Recent usage not reported';
    const mbSummary=mb?(mb.lastCallAt?`Last provider call ${dateTime(mb.lastCallAt)}`:`No recent call recorded${finite(mb.perRunCap)?` · max ${count(mb.perRunCap).toLocaleString()}/run`:''}`):'Recent usage not reported';
    const rows=[
      {id:'spotify',name:'Spotify',state:'Safety budget',summary:spotifySummary,headline:'No fixed provider percentage shown',detail:'BANDMARKR shows its own current safety budget instead of pretending Spotify has a fixed free-tier percentage.'},
      {id:'musicbrainz',name:'MusicBrainz',state:'Courtesy pacing',summary:mbSummary,headline:'Courtesy limits',detail:'MusicBrainz is paced conservatively; BANDMARKR does not present a made-up daily quota percentage.'},
      {id:'listenbrainz',name:'ListenBrainz',state:lb?'Configured':'Not connected',summary:validLbSync?`Last successful sync ${dateTime(lb.lastSyncAt)}`:(lb?'No successful sync recorded yet':'No device connection'),headline:lb?`Configured as ${lb.userName||'ListenBrainz user'}`:'Optional device connection',detail:lb?'This device has a saved ListenBrainz connection.':'Connect in Data when you want this device to keep listening history current.'},
    ];
    return rows.map((p)=>`<div class="research-tool-overview-row gau2-provider-row" data-gau2-provider="${p.id}"><button type="button" class="research-tool-overview-button gau2-provider-button" aria-expanded="false"><span class="research-tool-overview-title">${esc(p.name)}</span><span class="gau2-provider-state">${esc(p.state)}</span><span class="research-tool-overview-usage">${esc(p.summary)}</span></button><div class="research-tool-details gau2-provider-expand">${providerDetailsHtml(p.id,p.headline,p.detail)}</div></div>`).join('');
  }
  function setTextIfChanged(node,text){if(node&&node.textContent!==text)node.textContent=text;}
  function setHtmlIfChanged(node,key,signature,html){if(!node||node.dataset[key]===signature)return false;node.innerHTML=html;node.dataset[key]=signature;return true;}
  function appendExistingProviderPurpose(screen){screen.querySelectorAll('.research-tool-overview-row:not(.gau2-provider-row)').forEach((row)=>{const id=row.querySelector('[data-research-tool]')?.dataset.researchTool,card=row.querySelector('.usage-service-card');if(!id||!card||!PROVIDER_PURPOSES[id]||card.querySelector('[data-gau2-provider-purpose]'))return;const note=root.document.createElement('div');note.dataset.gau2ProviderPurpose='true';note.className='usage-detail-row gau2-provider-purpose';note.innerHTML=`<span><strong>Used for:</strong> ${esc(PROVIDER_PURPOSES[id])}</span>`;card.appendChild(note);});}
  function renderAutomation(screen){
    const labels=[...screen.querySelectorAll('.section-label')],toolsLabel=labels.find((n)=>['Research tools','Provider/API status'].includes(n.textContent.trim()));setTextIfChanged(toolsLabel,'Provider/API status');setTextIfChanged(screen.querySelector('.settings-section-intro'),'Usage, connection and safety state for the services BANDMARKR relies on.');
    const overview=screen.querySelector('.research-tools-overview');if(overview&&!overview.querySelector('[data-gau2-provider="spotify"]'))overview.insertAdjacentHTML('beforeend',supplementalProvidersHtml());appendExistingProviderPurpose(screen);
    const pipelineLabel=[...screen.querySelectorAll('.section-label')].find((n)=>['Research pipeline','Automation status'].includes(n.textContent.trim()));if(pipelineLabel){setTextIfChanged(pipelineLabel,'Automation status');const card=pipelineLabel.nextElementSibling;if(card?.classList.contains('settings-card')){card.classList.add('gau2-automation-card');const rows=automationRows();setHtmlIfChanged(card,'gau2Signature',JSON.stringify(rows),rows.map(automationRowHtml).join(''));}const after=card?.nextElementSibling;if(after?.classList.contains('settings-hint')&&/Updated automatically|pipeline/i.test(after.textContent||''))after.remove();}
    screen.querySelectorAll('.gau2-provider-button').forEach((button)=>{if(button.dataset.gau2Wired==='true')return;button.dataset.gau2Wired='true';button.addEventListener('click',()=>{const details=button.closest('.gau2-provider-row')?.querySelector('.gau2-provider-expand'),open=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(open));details?.classList.toggle('is-open',open);});});
  }
  function cardContaining(screen,text){return[...screen.querySelectorAll('.settings-card')].find((card)=>(card.textContent||'').includes(text))||null;}
  function renderReview(screen){
    cardContaining(screen,'Last manual MusicBrainz run:')?.remove();[...screen.querySelectorAll('p, a')].forEach((node)=>{/Weekly automatic MusicBrainz lookups are off|Open MusicBrainz runs/i.test((node.textContent||'').trim())&&node.remove();});const retryLabel=screen.querySelector('.identity-retry-label');if(retryLabel){const next=retryLabel.nextElementSibling;if(next?.querySelector('.identity-retry'))next.remove();retryLabel.remove();}
    const mbSummary=(()=>{try{return root.MusicbrainzState?.artistIdentitySummary?.(bandState())||null;}catch(_){return null;}})(),summaryCard=screen.querySelector('.identity-review > .settings-card');if(summaryCard&&mbSummary){const identified=count(mbSummary.autoConfirmed)+count(mbSummary.manualConfirmed),waiting=count(mbSummary.awaitingReview);setHtmlIfChanged(summaryCard,'gau2MbSummary',`${identified}:${waiting}`,`<p class="settings-hint gau2-review-line"><strong>Artist matches</strong><span>${identified.toLocaleString()} identified · ${waiting.toLocaleString()} need review</span></p>`);}
    const listeningReview=screen.querySelector('#listening-review-maintenance');if(listeningReview){const hasItems=Boolean(listeningReview.querySelector('.listening-review-item')),loading=/Checking local derived listening data/i.test(listeningReview.textContent||'');const shouldHide=!hasItems&&!loading;if(listeningReview.hidden!==shouldHide)listeningReview.hidden=shouldHide;const status=listeningReview.querySelector('[data-listening-review-status]');if(hasItems&&status&&!status.hidden)status.hidden=true;setTextIfChanged(listeningReview.querySelector('.section-label'),'Listening matches');}
    const spotifySection=screen.querySelector('#spotify-identity-review-section');spotifySection?.querySelectorAll('.spotify-review-card').forEach((card)=>{if(/Candidate acquisition required/i.test(card.textContent||''))card.hidden=true;});
    let top=screen.querySelector('[data-gau2-review-summary]');if(!top){top=root.document.createElement('div');top.dataset.gau2ReviewSummary='true';top.className='settings-card gau2-review-summary';screen.querySelector('.settings-subtab-switch')?.after(top);}const total=screen.querySelectorAll('.identity-review-card').length+screen.querySelectorAll('.listening-review-item').length+[...screen.querySelectorAll('.spotify-review-card')].filter((card)=>!card.hidden).length;const html=total?`<p><strong>${total.toLocaleString()} item${total===1?'':'s'} need your review.</strong></p><p class="settings-hint">Only matches that need your judgment are shown below.</p>`:'<p><strong>Everything is resolved.</strong></p><p class="settings-hint">No artist or listening matches need your attention.</p>';setHtmlIfChanged(top,'gau2Summary',String(total),html);
  }
  function ensureLegacyExportAnchor(screen){let visible=[...screen.querySelectorAll('.section-label')].find((n)=>n.textContent.trim()==='Data export'&&!n.dataset.gau2LegacyExportAnchor);if(!visible)visible=[...screen.querySelectorAll('.section-label')].find((n)=>n.textContent.trim()==='Export & backup');if(!visible)return;if(!screen.querySelector('[data-gau2-legacy-export-anchor]')){const anchor=root.document.createElement('p');anchor.className='section-label gau2-legacy-anchor';anchor.dataset.gau2LegacyExportAnchor='true';anchor.textContent='Data export';visible.before(anchor);}setTextIfChanged(visible,'Export & backup');}
  function dataOverviewHtml(){return `<p class="section-label" data-gau2-data-overview-label>Data overview</p><div class="settings-card gau2-data-overview" data-gau2-data-overview><div class="gau2-data-metrics"><span><strong>${bandState().length.toLocaleString()}</strong><small>bands</small></span><span><strong>${concertState().length.toLocaleString()}</strong><small>concerts</small></span><span><strong>${listeningState().length.toLocaleString()}</strong><small>listens on this device</small></span></div><p class="settings-hint">Core Live Vault data is stored through the private Cloudflare connection. Listening history and some connection state are stored on this device.</p></div>`;}
  function moveDeviceActions(screen){const button=screen.querySelector('#change-connection-btn');if(!button||screen.querySelector('[data-gau2-device-reset]'))return;const sourceCard=button.closest('.settings-card');if(!sourceCard)return;const section=root.document.createElement('div');section.dataset.gau2DeviceReset='true';section.innerHTML='<p class="section-label">Device & reset</p><div class="settings-card gau2-device-card"></div>';const version=screen.querySelector('.settings-version');if(version)version.before(section);else screen.append(section);const target=section.querySelector('.gau2-device-card');[sourceCard.querySelector('[data-device-privacy-hint]'),button,sourceCard.querySelector('#erase-device-btn'),sourceCard.querySelector('[data-device-erase-hint]')].filter(Boolean).forEach((node)=>target.append(node));const intro=root.document.createElement('p');intro.className='settings-hint';intro.textContent='Disconnect this device from Live Vault, or erase data stored only on this device.';target.prepend(intro);}
  function renderData(screen){ensureLegacyExportAnchor(screen);const identityLabel=[...screen.querySelectorAll('.section-label')].find((n)=>n.textContent.trim()==='Artist identity coverage');if(identityLabel&&!screen.querySelector('[data-gau2-data-overview]'))identityLabel.insertAdjacentHTML('beforebegin',dataOverviewHtml());const bandLabel=[...screen.querySelectorAll('.section-label')].find((n)=>n.textContent.trim()==='Band status');if(bandLabel){const card=bandLabel.nextElementSibling;bandLabel.remove();if(card?.classList.contains('settings-card'))card.remove();}const connectionLabel=[...screen.querySelectorAll('.section-label')].find((n)=>['Connection','Connections'].includes(n.textContent.trim()));setTextIfChanged(connectionLabel,'Connections');const connectionCard=screen.querySelector('#change-connection-btn')?.closest('.settings-card');if(connectionCard&&!connectionCard.querySelector('[data-gau2-core-status]')){const first=connectionCard.querySelector('p');if(first){const endpoint=(()=>{try{return typeof remote!=='undefined'?remote?.endpoint:null;}catch(_){return null;}})();setTextIfChanged(first,endpoint||'Core data connection unavailable');}const status=root.document.createElement('p');status.dataset.gau2CoreStatus='true';status.className='settings-hint gau2-connection-status';status.innerHTML='<strong>Core Live Vault connection:</strong> Configured on this device';connectionCard.prepend(status);}moveDeviceActions(screen);}
  function applyPresentation(){const screen=root.document?.getElementById('screen-settings');if(!screen||screen.classList.contains('hidden'))return;setTextIfChanged(screen.querySelector('[data-settings-tab="research"]'),'Automation');const tab=screen.querySelector('[data-settings-tab].active')?.dataset.settingsTab;if(tab==='research')renderAutomation(screen);else if(tab==='review')renderReview(screen);else if(tab==='data')renderData(screen);}
  let scheduled=false;function schedulePresentation(){if(scheduled)return;scheduled=true;root.setTimeout?.(()=>{scheduled=false;applyPresentation();},0);}
  function install(){if(typeof artistIdentityReviewHtml==='function'&&!artistIdentityReviewHtml.__gau2V118){const old=artistIdentityReviewHtml,wrapped=function(...args){return repairMusicbrainzConfidenceHtml(old.apply(this,args));};wrapped.__gau2V118=true;artistIdentityReviewHtml=wrapped;}if(typeof renderSettingsScreen==='function'&&!renderSettingsScreen.__gau2V118){const old=renderSettingsScreen,wrapped=async function(...args){const result=await old.apply(this,args);applyPresentation();schedulePresentation();return result;};wrapped.__gau2V118=true;renderSettingsScreen=wrapped;}const screen=root.document?.getElementById('screen-settings');if(screen&&root.MutationObserver&&!screen.dataset.gau2Observer){screen.dataset.gau2Observer='true';new root.MutationObserver(schedulePresentation).observe(screen,{childList:true,subtree:true});}schedulePresentation();}
  if(typeof root?.document!=='undefined'){if(root.document.readyState==='loading')root.addEventListener('DOMContentLoaded',install,{once:true});else install();}
  return {AUTOMATION_GROUPS,PROVIDER_PURPOSES,formatMusicbrainzConfidence,repairMusicbrainzConfidenceHtml,statusFromRun,listenBrainzAutomationState,nextMwfUtc,nextFocusedWebUtc,latestRun,automationRows,applyPresentation,install};
});