'use strict';
(function attachListeningHistoryV2(root, factory) {
  const api = factory(root); if (typeof module === 'object' && module.exports) module.exports = api; if (root) root.LiveVaultListeningHistoryV2 = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, (root) => {
  const DB_NAME='livevault-listening-history-v1', STORE_NAME='listens', META_STORE='meta', META_KEY='spotify-import';
  const OPTIONAL_ID_KEYS=['musicbrainzRecordingId','musicbrainzArtistIds','musicbrainzReleaseId','musicbrainzReleaseGroupId','listenbrainzRecordingMsid','listenbrainzUrlRels','listenbrainzCaaId','listenbrainzCaaReleaseMbid'];
  const normalizeText=(v)=>String(v||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('en');
  function safeUuid(v){const t=String(v||'').trim().toLowerCase();return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(t)?t:null;}
  function safeHttpsUrl(v){if(typeof v!=='string'||!v.trim())return null;try{const u=new URL(v.trim());return u.protocol==='https:'?u.toString():null;}catch{return null;}}
  function exactArtworkReleaseMbid(event){const ids=[...new Set([event?.musicbrainzReleaseId,event?.listenbrainzCaaReleaseMbid].map(safeUuid).filter(Boolean))];return ids.length===1?ids[0]:null;}
  function providerNeutralArtworkUrl(event){const caaRelease=safeUuid(event?.listenbrainzCaaReleaseMbid);const caaId=String(event?.listenbrainzCaaId||'').trim();if(!caaRelease||!/^[A-Za-z0-9_-]{1,128}$/.test(caaId))return null;const releaseMbid=exactArtworkReleaseMbid(event);return releaseMbid?`https://coverartarchive.org/release/${releaseMbid}/front-500`:null;}
  function sanitizeEvent(raw){
    if(!raw||typeof raw!=='object')return null;const source=raw.source==='listenbrainz'?'listenbrainz':'spotify_import';const timestamp=Date.parse(String(raw.listenedAt||''));const artist=String(raw.artistCreditName||'').trim(),track=String(raw.recordingTitle||'').trim(),stableListenId=String(raw.stableListenId||'').trim();if(!Number.isFinite(timestamp)||!artist||!track||!stableListenId)return null;
    const dv=Number(raw.listenedDurationMs),duration=Number.isFinite(dv)&&dv>0?Math.round(dv):null,spotifyTrackId=String(raw.spotifyTrackId||'').trim()||null;if(source==='spotify_import'&&(!spotifyTrackId||!duration||duration<30000))return null;
    const event={stableListenId,listenedAt:new Date(timestamp).toISOString(),listenedDurationMs:duration,artistCreditName:artist,recordingTitle:track,releaseTitle:raw.releaseTitle==null?null:String(raw.releaseTitle).trim()||null,spotifyTrackId,source};
    event.musicbrainzRecordingId=safeUuid(raw.musicbrainzRecordingId);event.musicbrainzReleaseId=safeUuid(raw.musicbrainzReleaseId);event.musicbrainzReleaseGroupId=safeUuid(raw.musicbrainzReleaseGroupId);event.listenbrainzRecordingMsid=safeUuid(raw.listenbrainzRecordingMsid);event.listenbrainzCaaReleaseMbid=safeUuid(raw.listenbrainzCaaReleaseMbid);event.listenbrainzCaaId=raw.listenbrainzCaaId==null?null:(/^[A-Za-z0-9_-]{1,128}$/.test(String(raw.listenbrainzCaaId).trim())?String(raw.listenbrainzCaaId).trim():null);event.listenbrainzUrlRels=[...new Set((Array.isArray(raw.listenbrainzUrlRels)?raw.listenbrainzUrlRels:[]).map(safeHttpsUrl).filter(Boolean))].slice(0,32);event.musicbrainzArtistIds=[...new Set((Array.isArray(raw.musicbrainzArtistIds)?raw.musicbrainzArtistIds:[]).map(safeUuid).filter(Boolean))];
    const artworkUrl=providerNeutralArtworkUrl(event);if(artworkUrl){event.albumArtworkUrl=artworkUrl;event.artworkPath=artworkUrl;event.albumArtworkSource='cover-art-archive-exact-release';}return event;
  }
  function fingerprint(event){const t=Date.parse(event?.listenedAt||'');return Number.isFinite(t)?`${Math.floor(t/1000)}|${normalizeText(event.artistCreditName)}|${normalizeText(event.recordingTitle)}`:null;}
  function openDb(){return new Promise((resolve,reject)=>{const r=root.indexedDB.open(DB_NAME,1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Could not open private listening storage.'));});}
  function requestResult(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Private listening storage failed.'));});}
  function summary(events,previous={}){const ordered=[...events].sort((a,b)=>a.listenedAt.localeCompare(b.listenedAt)||a.stableListenId.localeCompare(b.stableListenId));return{key:META_KEY,importedAt:previous.importedAt||new Date().toISOString(),updatedAt:new Date().toISOString(),eventCount:ordered.length,firstListenedAt:ordered[0]?.listenedAt||null,lastListenedAt:ordered.at(-1)?.listenedAt||null,sourceSha256:previous.sourceSha256||null};}
  async function replaceEvents(events,options={}){const sanitized=(events||[]).map(sanitizeEvent).filter(Boolean),byId=new Map(sanitized.map(e=>[e.stableListenId,e])),ordered=[...byId.values()].sort((a,b)=>a.listenedAt.localeCompare(b.listenedAt)||a.stableListenId.localeCompare(b.stableListenId)),db=await openDb(),previous=await requestResult(db.transaction(META_STORE,'readonly').objectStore(META_STORE).get(META_KEY)).catch(()=>null);await new Promise((resolve,reject)=>{const tx=db.transaction([STORE_NAME,META_STORE],'readwrite');tx.objectStore(STORE_NAME).clear();for(const e of ordered)tx.objectStore(STORE_NAME).put(e);tx.objectStore(META_STORE).put({...summary(ordered,previous||{}),sourceSha256:options.sourceSha256||previous?.sourceSha256||null});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||new Error('Could not replace listening history.'));tx.onabort=()=>reject(tx.error||new Error('Listening-history replacement was cancelled.'));});db.close();return{eventCount:ordered.length};}
  async function mergeEvents(events){const incoming=(events||[]).map(sanitizeEvent).filter(Boolean),db=await openDb(),readTx=db.transaction([STORE_NAME,META_STORE],'readonly'),existing=await requestResult(readTx.objectStore(STORE_NAME).getAll()),previous=await requestResult(readTx.objectStore(META_STORE).get(META_KEY)),byId=new Map(existing.map(e=>[e.stableListenId,e])),fingerprints=new Set(existing.map(fingerprint).filter(Boolean));let added=0,skipped=0;for(const e of incoming){const mark=fingerprint(e);if(byId.has(e.stableListenId)||(mark&&fingerprints.has(mark))){skipped++;continue;}byId.set(e.stableListenId,e);if(mark)fingerprints.add(mark);added++;}const ordered=[...byId.values()].sort((a,b)=>a.listenedAt.localeCompare(b.listenedAt)||a.stableListenId.localeCompare(b.stableListenId));if(added)await new Promise((resolve,reject)=>{const tx=db.transaction([STORE_NAME,META_STORE],'readwrite');for(const e of incoming)if(byId.get(e.stableListenId)===e)tx.objectStore(STORE_NAME).put(e);tx.objectStore(META_STORE).put(summary(ordered,previous||{}));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||new Error('Could not merge listening history.'));});db.close();return{added,skipped,eventCount:ordered.length};}
  function install(){const history=root?.LiveVaultSpotifyHistory;if(!history)return false;history.sanitizeEvent=sanitizeEvent;history.replaceEvents=replaceEvents;history.mergeEvents=mergeEvents;history.OPTIONAL_ID_KEYS=OPTIONAL_ID_KEYS;return true;}
  return{OPTIONAL_ID_KEYS,sanitizeEvent,fingerprint,exactArtworkReleaseMbid,providerNeutralArtworkUrl,replaceEvents,mergeEvents,install};
});
if(typeof window!=='undefined')window.LiveVaultListeningHistoryV2.install();
