const SPOTIFY_METADATA_ID = /^[A-Za-z0-9]{1,64}$/;
const TRACK_IDENTITY_KEY = /^(?:spotify:[A-Za-z0-9]{1,64}|text:[a-f0-9]{64})$/;
const ISRC = /^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$/;
const MAX_SPOTIFY_METADATA_RECORDS = 100000;
const MAX_TRACK_IDENTITY_RECORDS = 100000;
const MAX_MUSICBRAINZ_CATALOGUE_ARTISTS = 5000;
const MAX_MUSICBRAINZ_SCOPE_RELEASES = 100000;
const MAX_MUSICBRAINZ_RECORDINGS_PER_ARTIST = 50000;
const MAX_MUSICBRAINZ_RELEASES_PER_RECORDING = 1000;
function spotifyMetadataDateIsValid(value){return value==null||(typeof value==='string'&&Number.isFinite(Date.parse(value)));}
function spotifyMetadataHttpsUrlIsValid(value){if(value==null)return true;if(typeof value!=='string'||!value)return false;try{return new URL(value).protocol==='https:';}catch{return false;}}
function spotifyMetadataSpotifyUrlIsValid(value,kind,id){if(typeof value!=='string')return false;try{const url=new URL(value);return url.protocol==='https:'&&url.hostname==='open.spotify.com'&&url.pathname===`/${kind}/${id}`;}catch{return false;}}
function spotifyIdListIsValid(value){return value==null||(Array.isArray(value)&&value.length<=32&&value.every((item)=>typeof item==='string'&&SPOTIFY_METADATA_ID.test(item)));}
function musicbrainzIdListIsValid(value){return value==null||(Array.isArray(value)&&value.length<=32&&value.every((item)=>typeof item==='string'&&MUSICBRAINZ_MBID.test(item)));}
function spotifyListeningMetadataRecordIsValid(key,record){if(!SPOTIFY_METADATA_ID.test(String(key||''))||!record||typeof record!=='object'||Array.isArray(record))return false;if(record.spotifyTrackId!==key)return false;if(!spotifyMetadataSpotifyUrlIsValid(record.spotifyTrackUrl,'track',key))return false;if(record.spotifyAlbumId!=null){if(typeof record.spotifyAlbumId!=='string'||!SPOTIFY_METADATA_ID.test(record.spotifyAlbumId))return false;if(!spotifyMetadataSpotifyUrlIsValid(record.spotifyAlbumUrl,'album',record.spotifyAlbumId))return false;}else if(record.spotifyAlbumUrl!=null)return false;if(!spotifyMetadataHttpsUrlIsValid(record.artworkUrl))return false;if(!spotifyIdListIsValid(record.spotifyArtistIds))return false;if(record.isrc!=null&&(typeof record.isrc!=='string'||!ISRC.test(record.isrc)))return false;if(!spotifyMetadataDateIsValid(record.fetchedAt))return false;if(record.source!=='spotify_exact_track_id')return false;return true;}
function spotifyListeningMetadataIsValid(value){if(!value||typeof value!=='object'||Array.isArray(value))return false;if(value.kind!=='livevault-spotify-listening-metadata'||value.schemaVersion!==1)return false;if(!spotifyMetadataDateIsValid(value.updatedAt))return false;if(!value.records||typeof value.records!=='object'||Array.isArray(value.records))return false;const entries=Object.entries(value.records);if(entries.length>MAX_SPOTIFY_METADATA_RECORDS)return false;return entries.every(([key,record])=>spotifyListeningMetadataRecordIsValid(key,record));}

const DISCOVER_RECOMMENDATIONS_FILE = 'discoverRecommendations.json';
const ALLOWED_FILES = new Set(['bands.json','concerts.json','news.json','apiUsage.json','venues.json',DISCOVER_RECOMMENDATIONS_FILE]);
const JSON_ROOT_TYPES = {'bands.json':'array','concerts.json':'array','news.json':'array','apiUsage.json':'object','venues.json':'array',[DISCOVER_RECOMMENDATIONS_FILE]:'object'};
const QA_SMOKE_JSON_ROOT_TYPES = {'bands.json':'array','concerts.json':'array','news.json':'array','apiUsage.json':'object'};
const VENUE_RESEARCH_STATUSES = new Set(['complete','partial','unresolved','temporary_error','review_needed']);
const MAX_JSON_BYTES = 10 * 1024 * 1024;
const MAX_DISCOVER_RECOMMENDATIONS_BYTES = 512 * 1024;
const MAX_LISTENING_MANIFEST_BYTES = 1024 * 1024;
const MAX_LISTENING_ARCHIVE_BYTES = 100 * 1024 * 1024;
const MAX_SPOTIFY_METADATA_BYTES = 25 * 1024 * 1024;
const MAX_TRACK_IDENTITIES_BYTES = 25 * 1024 * 1024;
const MAX_MUSICBRAINZ_CATALOGUE_BYTES = 25 * 1024 * 1024;
const MAX_LISTENING_BAND_ACTIVITY_BYTES = 2 * 1024 * 1024;
const MAX_TICKET_PDF_BYTES = 10 * 1024 * 1024;
const SAFE_ID = /^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/;
const MUSICBRAINZ_MBID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const MUSICBRAINZ_RELEASE_CONTEXT_PATH = '/musicbrainz/release-context';
const MUSICBRAINZ_ROOT = 'https://musicbrainz.org/ws/2';
const MUSICBRAINZ_USER_AGENT = 'BANDMARKR/104 (https://github.com/mstpln/concert-tracker-mobile)';
const MUSICBRAINZ_TIMEOUT_MS = 10000;
const LISTENING_MANIFEST_PATH = 'listening/manifest.json';
const SPOTIFY_METADATA_PATH = 'listening/spotify-metadata.json';
const TRACK_IDENTITIES_PATH = 'listening/track-identities.json';
const MUSICBRAINZ_CATALOGUE_PATH = 'listening/musicbrainz-catalogue.json';
const LISTENING_BAND_ACTIVITY_PATH = 'listening/band-activity.json';
const SPOTIFY_ARCHIVE_PATTERN = /^listening\/spotify-history\/([a-f0-9]{64})\.json\.gz$/;
const LISTENBRAINZ_ARCHIVE_PATTERN = /^listening\/listenbrainz\/(\d{4}-(?:0[1-9]|1[0-2]))\/([a-f0-9]{64})\.json\.gz$/;
const TRACK_IDENTITY_STATUSES = new Set(['unresolved','resolved','no_match','needs_review','retry','error']);
const MUSICBRAINZ_CATALOGUE_SCOPES = ['release_artist','release_track_artist'];
function corsHeaders(){return {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, PUT, DELETE, OPTIONS','Access-Control-Allow-Headers':'Authorization, Content-Type, If-Match, If-None-Match','Access-Control-Expose-Headers':'ETag'};}
function response(body,init={}){return new Response(body,{...init,headers:{...corsHeaders(),'Cache-Control':'private, no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff',...(init.headers||{})}});}
function bearerToken(request){return (request.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');}
function credentialMatchCount(token,env){return [env.BROWSER_TOKEN,env.AUTOMATION_TOKEN,env.DATA_MAINTENANCE_TOKEN,env.API_TOKEN,env.READ_ONLY_TOKEN].filter((value)=>value&&token===value).length;}
function authorizationRole(request,env){const token=bearerToken(request);if(!token||credentialMatchCount(token,env)!==1)return null;if(env.BROWSER_TOKEN&&token===env.BROWSER_TOKEN)return'browser';if(env.AUTOMATION_TOKEN&&token===env.AUTOMATION_TOKEN)return'automation';if(env.DATA_MAINTENANCE_TOKEN&&token===env.DATA_MAINTENANCE_TOKEN)return'data-maintenance';if(env.API_TOKEN&&token===env.API_TOKEN)return'legacy';return null;}
function isReadOnlyAuthorized(request,env){const token=bearerToken(request);return !!token&&credentialMatchCount(token,env)===1&&(!!authorizationRole(request,env)||(!!env.READ_ONLY_TOKEN&&token===env.READ_ONLY_TOKEN));}
function jsonRootIsValid(filename,value){return JSON_ROOT_TYPES[filename]==='array'?Array.isArray(value):!!value&&typeof value==='object'&&!Array.isArray(value);}
function venueHttpsUrlIsValid(value){if(typeof value!=='string'||!value.trim())return false;try{return new URL(value.trim()).protocol==='https:';}catch{return false;}}
function venueAddressIsValid(value){if(typeof value==='string')return!!value.trim();if(!value||typeof value!=='object'||Array.isArray(value))return false;return['street','streetAddress','line1','line2','postalCode','postal','zip','city','country'].some((key)=>String(value[key]||'').trim());}
function venueRecordIsValid(record){if(!record||typeof record!=='object'||Array.isArray(record))return false;if(typeof record.venueId!=='string'||!/^venue-[a-f0-9]{8}$/.test(record.venueId))return false;if(typeof record.name!=='string'||!record.name.trim()||typeof record.city!=='string'||!record.city.trim())return false;if(record.country!=null&&typeof record.country!=='string')return false;if(record.address!=null&&!venueAddressIsValid(record.address))return false;if(record.maxCapacity!=null&&(!Number.isSafeInteger(record.maxCapacity)||record.maxCapacity<=0))return false;if(record.officialUrl!=null&&!venueHttpsUrlIsValid(record.officialUrl))return false;if(record.description!=null&&(typeof record.description!=='string'||!record.description.trim()||record.description.trim().length>900))return false;if(record.researchStatus!=null&&!VENUE_RESEARCH_STATUSES.has(record.researchStatus))return false;if(record.researchedAt!=null&&(typeof record.researchedAt!=='string'||!Number.isFinite(Date.parse(record.researchedAt))))return false;if(record.sources!=null&&(!Array.isArray(record.sources)||record.sources.length>16||record.sources.some((url)=>!venueHttpsUrlIsValid(url))))return false;if(record.schemaVersion!=null&&record.schemaVersion!==1)return false;return true;}
function venueDocumentIsValid(value){if(!Array.isArray(value))return false;const ids=new Set();for(const record of value){if(!venueRecordIsValid(record)||ids.has(record.venueId))return false;ids.add(record.venueId);}return true;}
function archiveEntryIsValid(entry,source){if(!entry||typeof entry!=='object'||Array.isArray(entry))return false;if(entry.source!==source)return false;const pattern=source==='spotify_import'?SPOTIFY_ARCHIVE_PATTERN:LISTENBRAINZ_ARCHIVE_PATTERN;if(!pattern.test(String(entry.path||'')))return false;if(!/^[a-f0-9]{64}$/.test(String(entry.sha256||'')))return false;if(entry.contentEncoding!=='gzip')return false;if(!Number.isInteger(entry.eventCount)||entry.eventCount<0||entry.eventCount>10000000)return false;return true;}
function listeningManifestIsValid(value){if(!value||typeof value!=='object'||Array.isArray(value))return false;if(value.kind!=='livevault-listening-vault'||value.schemaVersion!==1)return false;if(!archiveEntryIsValid(value.archive,'spotify_import'))return false;if(value.incrementals!=null){if(!Array.isArray(value.incrementals)||value.incrementals.length>10000)return false;for(const item of value.incrementals){if(!archiveEntryIsValid(item,'listenbrainz'))return false;if(!/^\d{4}-(?:0[1-9]|1[0-2])$/.test(String(item.month||'')))return false;}}return true;}
function trackIdentityRecordIsValid(key,record){if(!TRACK_IDENTITY_KEY.test(key)||!record||typeof record!=='object'||Array.isArray(record))return false;if(record.workKey!==key)return false;const spotifyKey=key.startsWith('spotify:')?key.slice('spotify:'.length):null;if(spotifyKey&&record.spotifyTrackId!==spotifyKey)return false;if(record.localBandId!=null&&(typeof record.localBandId!=='string'||!SAFE_ID.test(record.localBandId)))return false;if(record.spotifyTrackId!=null&&(typeof record.spotifyTrackId!=='string'||!SPOTIFY_METADATA_ID.test(record.spotifyTrackId)))return false;if(!spotifyIdListIsValid(record.spotifyArtistIds))return false;if(record.isrc!=null&&(typeof record.isrc!=='string'||!ISRC.test(record.isrc)))return false;if(record.musicbrainzRecordingId!=null&&(typeof record.musicbrainzRecordingId!=='string'||!MUSICBRAINZ_MBID.test(record.musicbrainzRecordingId)))return false;if(!musicbrainzIdListIsValid(record.musicbrainzArtistIds))return false;if(record.status!=null&&!TRACK_IDENTITY_STATUSES.has(record.status))return false;if(!spotifyMetadataDateIsValid(record.updatedAt)||!spotifyMetadataDateIsValid(record.nextEligibleCheckAt))return false;return true;}
function trackIdentitiesIsValid(value){if(!value||typeof value!=='object'||Array.isArray(value))return false;if(value.kind!=='livevault-track-identities'||value.schemaVersion!==1)return false;if(!spotifyMetadataDateIsValid(value.updatedAt))return false;if(!value.records||typeof value.records!=='object'||Array.isArray(value.records))return false;const entries=Object.entries(value.records);if(entries.length>MAX_TRACK_IDENTITY_RECORDS)return false;return entries.every(([key,record])=>trackIdentityRecordIsValid(key,record));}
function musicbrainzCatalogueReleaseIsValid(release){return !!release&&typeof release==='object'&&!Array.isArray(release)&&typeof release.title==='string'&&!!release.title.trim()&&typeof release.releaseMbid==='string'&&MUSICBRAINZ_MBID.test(release.releaseMbid)&&(release.releaseGroupMbid==null||(typeof release.releaseGroupMbid==='string'&&MUSICBRAINZ_MBID.test(release.releaseGroupMbid)));}
function musicbrainzCatalogueRecordingIsValid(recording,artistMbid,coveredReleaseSet){if(!recording||typeof recording!=='object'||Array.isArray(recording)||typeof recording.recordingMbid!=='string'||!MUSICBRAINZ_MBID.test(recording.recordingMbid)||typeof recording.title!=='string'||!recording.title.trim())return false;if(!Array.isArray(recording.artistMbids)||!recording.artistMbids.length||recording.artistMbids.length>32||!recording.artistMbids.every((id)=>typeof id==='string'&&MUSICBRAINZ_MBID.test(id))||!recording.artistMbids.map((id)=>id.toLowerCase()).includes(artistMbid))return false;if(!Array.isArray(recording.releases)||recording.releases.length<1||recording.releases.length>MAX_MUSICBRAINZ_RELEASES_PER_RECORDING)return false;const seen=new Set();for(const release of recording.releases){if(!musicbrainzCatalogueReleaseIsValid(release))return false;const id=release.releaseMbid.toLowerCase();if(seen.has(id)||!coveredReleaseSet.has(id))return false;seen.add(id);}return true;}
function musicbrainzCatalogueScopeIsValid(scope,artistMbid){if(!scope||typeof scope!=='object'||Array.isArray(scope)||scope.artistMbid!==artistMbid||scope.sourceEntity!=='release')return false;if(!Number.isInteger(scope.nextOffset)||scope.nextOffset<0||!Number.isInteger(scope.totalCount)||scope.totalCount<0||scope.nextOffset>scope.totalCount||typeof scope.complete!=='boolean'||scope.complete!==(scope.nextOffset===scope.totalCount))return false;if(!Array.isArray(scope.releaseMbids)||scope.releaseMbids.length!==scope.nextOffset||scope.releaseMbids.length>MAX_MUSICBRAINZ_SCOPE_RELEASES)return false;const releaseIds=scope.releaseMbids.map((id)=>typeof id==='string'?id.toLowerCase():'');if(releaseIds.some((id)=>!MUSICBRAINZ_MBID.test(id))||new Set(releaseIds).size!==releaseIds.length)return false;if(!Array.isArray(scope.recordings)||scope.recordings.length>MAX_MUSICBRAINZ_RECORDINGS_PER_ARTIST)return false;const covered=new Set(releaseIds);const recordingIds=new Set();for(const recording of scope.recordings){const recordingId=String(recording?.recordingMbid||'').toLowerCase();if(recordingIds.has(recordingId)||!musicbrainzCatalogueRecordingIsValid(recording,artistMbid,covered))return false;recordingIds.add(recordingId);}return true;}
function musicbrainzCatalogueRecordingIdentity(recording){return JSON.stringify({title:recording.title,artistMbids:[...recording.artistMbids].map((id)=>id.toLowerCase()).sort()});}
function musicbrainzCatalogueReleaseSignature(release){return JSON.stringify({releaseMbid:release.releaseMbid.toLowerCase(),releaseGroupMbid:release.releaseGroupMbid?release.releaseGroupMbid.toLowerCase():null,title:release.title});}
function addExpectedCatalogueRecording(map,recording){const id=recording.recordingMbid.toLowerCase();const identity=musicbrainzCatalogueRecordingIdentity(recording);let row=map.get(id);if(!row){row={identity,releases:new Map()};map.set(id,row);}else if(row.identity!==identity)return false;for(const release of recording.releases){const releaseId=release.releaseMbid.toLowerCase();const signature=musicbrainzCatalogueReleaseSignature(release);const prior=row.releases.get(releaseId);if(prior&&prior!==signature)return false;row.releases.set(releaseId,signature);}return true;}
function catalogueRecordingMatchesExpected(recording,expected){if(!expected||musicbrainzCatalogueRecordingIdentity(recording)!==expected.identity||recording.releases.length!==expected.releases.size)return false;for(const release of recording.releases){if(expected.releases.get(release.releaseMbid.toLowerCase())!==musicbrainzCatalogueReleaseSignature(release))return false;}return true;}
function musicbrainzCatalogueArtistIsValid(key,artist){const artistMbid=String(key||'').toLowerCase();if(!MUSICBRAINZ_MBID.test(artistMbid)||key!==artistMbid||!artist||typeof artist!=='object'||Array.isArray(artist)||artist.artistMbid!==artistMbid||artist.sourceEntity!=='release')return false;if(!artist.scopeCheckpoints||typeof artist.scopeCheckpoints!=='object'||Array.isArray(artist.scopeCheckpoints))return false;const scopeNames=Object.keys(artist.scopeCheckpoints);if(scopeNames.some((scope)=>!MUSICBRAINZ_CATALOGUE_SCOPES.includes(scope)))return false;const completed=[];const unionReleases=new Set();const expectedRecordings=new Map();for(const scopeName of scopeNames){const scope=artist.scopeCheckpoints[scopeName];if(!musicbrainzCatalogueScopeIsValid(scope,artistMbid))return false;if(scope.complete)completed.push(scopeName);for(const id of scope.releaseMbids)unionReleases.add(id.toLowerCase());for(const recording of scope.recordings)if(!addExpectedCatalogueRecording(expectedRecordings,recording))return false;}if(!Array.isArray(artist.coverageScopes)||artist.coverageScopes.length!==new Set(artist.coverageScopes).size||artist.coverageScopes.some((scope)=>!MUSICBRAINZ_CATALOGUE_SCOPES.includes(scope)))return false;if(JSON.stringify([...artist.coverageScopes].sort())!==JSON.stringify(completed.sort()))return false;if(!Array.isArray(artist.releaseMbids)||artist.releaseMbids.length!==unionReleases.size||artist.releaseMbids.some((id)=>!unionReleases.has(String(id).toLowerCase())))return false;if(!Array.isArray(artist.recordings)||artist.recordings.length!==expectedRecordings.size||artist.recordings.length>MAX_MUSICBRAINZ_RECORDINGS_PER_ARTIST)return false;const covered=new Set([...unionReleases]);const actualIds=new Set();for(const recording of artist.recordings){const id=String(recording?.recordingMbid||'').toLowerCase();if(actualIds.has(id)||!musicbrainzCatalogueRecordingIsValid(recording,artistMbid,covered)||!catalogueRecordingMatchesExpected(recording,expectedRecordings.get(id)))return false;actualIds.add(id);}const allComplete=MUSICBRAINZ_CATALOGUE_SCOPES.every((scope)=>artist.scopeCheckpoints[scope]?.complete===true);if(allComplete){if(artist.complete!==true||artist.nextOffset!==artist.releaseMbids.length||artist.totalCount!==artist.releaseMbids.length||!spotifyMetadataDateIsValid(artist.refreshedAt)||!spotifyMetadataDateIsValid(artist.freshUntil)||Date.parse(artist.freshUntil)-Date.parse(artist.refreshedAt)!==30*24*60*60*1000||artist.refreshStartedAt!=null)return false;}else if(!spotifyMetadataDateIsValid(artist.refreshStartedAt)||artist.refreshStartedAt==null||artist.complete!=null||artist.nextOffset!=null||artist.totalCount!=null||artist.refreshedAt!=null||artist.freshUntil!=null)return false;return true;}
function musicbrainzCatalogueIsValid(value){if(!value||typeof value!=='object'||Array.isArray(value)||value.kind!=='livevault-musicbrainz-catalogue-cache'||value.schemaVersion!==1||!value.artists||typeof value.artists!=='object'||Array.isArray(value.artists))return false;const entries=Object.entries(value.artists);if(entries.length>MAX_MUSICBRAINZ_CATALOGUE_ARTISTS)return false;return entries.every(([key,artist])=>musicbrainzCatalogueArtistIsValid(key,artist));}
function exactObjectKeys(value,keys){return!!value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join(',')===[...keys].sort().join(',');}
function discoverRecommendationsIsValid(value){if(!value||typeof value!=='object'||Array.isArray(value)||value.kind!=='bandmarkr-discover-recommendations'||value.schemaVersion!==1||!spotifyMetadataDateIsValid(value.updatedAt)||!spotifyMetadataDateIsValid(value.lastSuccessfulRefreshAt)||!Array.isArray(value.groups)||value.groups.length>30||!value.decisions||typeof value.decisions!=='object'||Array.isArray(value.decisions)||Object.keys(value.decisions).length>10000)return false;const seeds=new Set();const candidates=new Set();for(const group of value.groups){if(!group||typeof group!=='object'||Array.isArray(group)||typeof group.seedMbid!=='string'||!MUSICBRAINZ_MBID.test(group.seedMbid)||seeds.has(group.seedMbid.toLowerCase())||typeof group.seedName!=='string'||!group.seedName.trim()||!spotifyMetadataDateIsValid(group.createdAt)||!Array.isArray(group.candidates)||group.candidates.length>20||(group.seedBandId!=null&&(typeof group.seedBandId!=='string'||!SAFE_ID.test(group.seedBandId))))return false;seeds.add(group.seedMbid.toLowerCase());for(const candidate of group.candidates){const mbid=String(candidate?.artistMbid||'').toLowerCase();if(!candidate||typeof candidate!=='object'||Array.isArray(candidate)||!MUSICBRAINZ_MBID.test(mbid)||String(candidate.artistMbid)!==mbid||candidates.has(mbid)||value.decisions[mbid]||typeof candidate.name!=='string'||!candidate.name.trim()||!Number.isFinite(Number(candidate.similarityScore))||!spotifyMetadataDateIsValid(candidate.discoveredAt)||!Array.isArray(candidate.tags)||candidate.tags.length>2||candidate.tags.some((tag)=>typeof tag!=='string'||!tag.trim())||(candidate.area!=null&&typeof candidate.area!=='string')||(candidate.beginYear!=null&&(!Number.isInteger(candidate.beginYear)||candidate.beginYear<1000||candidate.beginYear>9999)))return false;candidates.add(mbid);}}for(const[key,decision]of Object.entries(value.decisions)){if(!MUSICBRAINZ_MBID.test(key)||key!==key.toLowerCase()||!decision||typeof decision!=='object'||Array.isArray(decision)||!['dismissed','added'].includes(decision.status)||!spotifyMetadataDateIsValid(decision.decidedAt)||(decision.addedBandId!=null&&(typeof decision.addedBandId!=='string'||!SAFE_ID.test(decision.addedBandId)))||(decision.status==='dismissed'&&decision.addedBandId!=null))return false;}return true;}
function utf8ByteLength(text){let bytes=0;for(let index=0;index<text.length;index+=1){const code=text.charCodeAt(index);if(code<0x80)bytes+=1;else if(code<0x800)bytes+=2;else if(code>=0xd800&&code<=0xdbff&&index+1<text.length&&text.charCodeAt(index+1)>=0xdc00&&text.charCodeAt(index+1)<=0xdfff){bytes+=4;index+=1;}else bytes+=3;}return bytes;}
async function readBoundedText(request,maxBytes){const declared=Number(request.headers.get('Content-Length'));if(Number.isFinite(declared)&&declared>maxBytes)return{tooLarge:true};const text=await request.text();return utf8ByteLength(text)>maxBytes?{tooLarge:true}:{text};}
async function readBoundedBytes(request,maxBytes){const declared=Number(request.headers.get('Content-Length'));if(Number.isFinite(declared)&&declared>maxBytes)return{tooLarge:true};const bytes=await request.arrayBuffer();return bytes.byteLength>maxBytes?{tooLarge:true}:{bytes};}
function objectEtag(object){if(!object)return null;if(object.httpEtag)return object.httpEtag;return object.etag?`"${String(object.etag).replace(/^"|"$/g,'')}"`:null;}
function bareEtag(value){return String(value||'').trim().replace(/^W\//,'').replace(/^"|"$/g,'');}
function writeCondition(request){const ifMatch=request.headers.get('If-Match');const ifNone=request.headers.get('If-None-Match');if(ifMatch)return{etagMatches:bareEtag(ifMatch)};if(ifNone==='*')return{etagDoesNotMatch:'*'};return null;}
async function requiredWriteCondition(request,env,key){const condition=writeCondition(request);if(condition)return condition;const existing=typeof env.BUCKET.head==='function'?await env.BUCKET.head(key):await env.BUCKET.get(key);return existing?null:{etagDoesNotMatch:'*'};}
async function qaSmoke(env){const files={};let healthy=true;for(const [filename,type] of Object.entries(QA_SMOKE_JSON_ROOT_TYPES)){try{const object=await env.BUCKET.get(filename);if(!object){files[filename]={ok:false,reason:'missing'};healthy=false;continue;}const value=JSON.parse(await object.text());const valid=type==='array'?Array.isArray(value):!!value&&typeof value==='object'&&!Array.isArray(value);files[filename]={ok:valid,type,count:Array.isArray(value)?value.length:null};if(!valid)healthy=false;}catch{files[filename]={ok:false,reason:'invalid'};healthy=false;}}return response(JSON.stringify({ok:healthy,files}),{status:healthy?200:503,headers:{'Content-Type':'application/json; charset=utf-8'}});}
function ticketRoute(pathname){const match=pathname.match(/^\/ticket-files\/([A-Za-z0-9][A-Za-z0-9_-]{0,127})\/([A-Za-z0-9][A-Za-z0-9_-]{0,127})\.pdf$/);return match&&SAFE_ID.test(match[1])&&SAFE_ID.test(match[2])?{concertId:match[1],ticketId:match[2]}:null;}
function listeningRoute(pathname){const key=pathname.replace(/^\//,'');if(key===LISTENING_MANIFEST_PATH)return{kind:'manifest',key};if(key===SPOTIFY_METADATA_PATH)return{kind:'metadata',key};if(key===TRACK_IDENTITIES_PATH)return{kind:'identities',key};if(key===MUSICBRAINZ_CATALOGUE_PATH)return{kind:'catalogue',key};if(key===LISTENING_BAND_ACTIVITY_PATH)return{kind:'activity',key};if(SPOTIFY_ARCHIVE_PATTERN.test(key))return{kind:'archive',key};if(LISTENBRAINZ_ARCHIVE_PATTERN.test(key))return{kind:'incremental',key};return null;}
function musicbrainzReleaseMbid(value){const text=String(value||'').trim().toLowerCase();return MUSICBRAINZ_MBID.test(text)?text:null;}
function maintenanceJsonAllowed(filename,method){if(method==='GET')return filename==='bands.json'||filename==='concerts.json'||filename==='apiUsage.json'||filename==='venues.json';if(method==='PUT')return filename==='apiUsage.json'||filename==='venues.json';return false;}
function maintenanceListeningAllowed(route,method){if(method==='GET')return true;if(method==='PUT')return route.kind==='metadata'||route.kind==='identities'||route.kind==='catalogue';return false;}
function listeningBandActivityIsValid(value){const rootKeys=['kind','schemaVersion','generatedAt','catalogueFingerprint','mappedListenCount','records'];if(!exactObjectKeys(value,rootKeys)||value.kind!=='livevault-listening-band-activity'||value.schemaVersion!==1||!spotifyMetadataDateIsValid(value.generatedAt)||!/^fnv1a32:[0-9a-f]{8}$/.test(String(value.catalogueFingerprint||''))||!Number.isSafeInteger(value.mappedListenCount)||value.mappedListenCount<0||!value.records||typeof value.records!=='object'||Array.isArray(value.records))return false;const buckets=['fourteenDays','threeMonths','oneYear','allTime'];const entries=Object.entries(value.records);if(entries.length>10000)return false;let counted=0;const ranks=Object.fromEntries(buckets.map(name=>[name,[]]));for(const[key,record]of entries){if(!SAFE_ID.test(key)||!exactObjectKeys(record,['bandId','buckets'])||record.bandId!==key||!exactObjectKeys(record.buckets,buckets))return false;for(const name of buckets){const bucket=record.buckets[name];if(!exactObjectKeys(bucket,['listenCount','recencyRank'])||!Number.isSafeInteger(bucket.listenCount)||bucket.listenCount<0||((bucket.listenCount===0)!==(bucket.recencyRank==null))||(bucket.recencyRank!=null&&(!Number.isSafeInteger(bucket.recencyRank)||bucket.recencyRank<1)))return false;counted+=bucket.listenCount;if(!Number.isSafeInteger(counted))return false;if(bucket.recencyRank!=null)ranks[name].push(bucket.recencyRank);}}if(counted!==value.mappedListenCount)return false;for(const values of Object.values(ranks)){values.sort((left,right)=>left-right);if(values.some((rank,index)=>rank!==index+1))return false;}return true;}
async function handleMusicbrainzReleaseContext(request,fetchImpl=fetch){if(request.method!=='GET')return response('Method not allowed',{status:405});const url=new URL(request.url);const releaseMbid=musicbrainzReleaseMbid(url.searchParams.get('release_mbid'));if(!releaseMbid)return response('Invalid release MBID',{status:400});const upstream=new URL(`${MUSICBRAINZ_ROOT}/release/${encodeURIComponent(releaseMbid)}`);upstream.searchParams.set('inc','release-groups');upstream.searchParams.set('fmt','json');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),MUSICBRAINZ_TIMEOUT_MS);let providerResponse;try{providerResponse=await fetchImpl(upstream,{headers:{Accept:'application/json','User-Agent':MUSICBRAINZ_USER_AGENT},signal:controller.signal});}catch(error){return response(error?.name==='AbortError'?'MusicBrainz request timed out':'MusicBrainz request failed',{status:502});}finally{clearTimeout(timer);}if(providerResponse.status===404)return response('Not found',{status:404});if(providerResponse.status===429||providerResponse.status===503)return response('MusicBrainz rate limited',{status:503});if(!providerResponse.ok)return response('MusicBrainz request failed',{status:502});let payload;try{payload=await providerResponse.json();}catch{return response('Invalid MusicBrainz response',{status:502});}const returnedReleaseMbid=musicbrainzReleaseMbid(payload?.id);const releaseGroupMbid=musicbrainzReleaseMbid(payload?.['release-group']?.id||payload?.release_group?.id);if(returnedReleaseMbid!==releaseMbid||!releaseGroupMbid)return response('Invalid MusicBrainz response',{status:502});return response(JSON.stringify({releaseMbid,releaseGroupMbid}),{headers:{'Content-Type':'application/json; charset=utf-8'}});}
async function handleTicketFile(request,env,route){const key=`ticket-files/${route.concertId}/${route.ticketId}.pdf`;if(request.method==='GET'){const object=await env.BUCKET.get(key);if(!object)return response('Not found',{status:404});return response(object.body,{headers:{'Content-Type':'application/pdf','Content-Disposition':'inline'}});}if(request.method==='DELETE'){await env.BUCKET.delete(key);return response('OK');}if(request.method!=='PUT')return response('Method not allowed',{status:405});if((request.headers.get('Content-Type')||'').split(';')[0].trim().toLowerCase()!=='application/pdf')return response('PDF content required',{status:400});const body=await readBoundedBytes(request,MAX_TICKET_PDF_BYTES);if(body.tooLarge)return response('PDF exceeds 10 MB',{status:413});const bytes=new Uint8Array(body.bytes);if(bytes.length<5||new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')return response('Invalid PDF',{status:400});await env.BUCKET.put(key,body.bytes,{httpMetadata:{contentType:'application/pdf',contentDisposition:'inline',cacheControl:'private, no-store'}});return response('OK');}
async function handleJsonFile(request,env,filename){const discover=filename===DISCOVER_RECOMMENDATIONS_FILE;const maxBytes=discover?MAX_DISCOVER_RECOMMENDATIONS_BYTES:MAX_JSON_BYTES;if(request.method==='GET'){const object=await env.BUCKET.get(filename);if(!object)return response('Not found',{status:404});const etag=objectEtag(object);if(!discover)return response(object.body,{headers:{'Content-Type':'application/json; charset=utf-8',...(etag?{ETag:etag}:{})}});const text=await object.text();if(utf8ByteLength(text)>maxBytes)return response('Stored Discover recommendations are invalid',{status:422});let parsed;try{parsed=JSON.parse(text);}catch{return response('Stored Discover recommendations are invalid',{status:422});}if(!discoverRecommendationsIsValid(parsed))return response('Stored Discover recommendations are invalid',{status:422});return response(text,{headers:{'Content-Type':'application/json; charset=utf-8',...(etag?{ETag:etag}:{})}});}if(request.method!=='PUT')return response('Method not allowed',{status:405});const condition=await requiredWriteCondition(request,env,filename);if(!condition)return response('Precondition required',{status:428});const contentType=(request.headers.get('Content-Type')||'').split(';')[0].trim().toLowerCase();if(contentType!=='application/json')return response('JSON content required',{status:415});const body=await readBoundedText(request,maxBytes);if(body.tooLarge)return response(discover?'Discover recommendations exceed 512 KB':'JSON exceeds 10 MB',{status:413});let parsed;try{parsed=JSON.parse(body.text);}catch{return response('Invalid JSON',{status:400});}if(!jsonRootIsValid(filename,parsed))return response('Invalid JSON document type',{status:400});if(filename==='venues.json'&&!venueDocumentIsValid(parsed))return response('Invalid venue metadata document',{status:400});if(discover&&!discoverRecommendationsIsValid(parsed))return response('Invalid Discover recommendations document',{status:400});const stored=await env.BUCKET.put(filename,body.text,{onlyIf:condition,httpMetadata:{contentType:'application/json; charset=utf-8',cacheControl:'private, no-store'}});if(stored===null)return response('Document changed; reread and retry',{status:412});const etag=objectEtag(stored);return response('OK',{headers:etag?{ETag:etag}:{}});}
async function handleListeningJson(request,env,route,maxBytes,validator,errorLabel,{validateRead=false}={}){if(request.method==='GET'){const object=await env.BUCKET.get(route.key);if(!object)return response('Not found',{status:404});const etag=objectEtag(object);if(!validateRead)return response(object.body,{headers:{'Content-Type':'application/json; charset=utf-8',...(etag?{ETag:etag}:{})}});const text=await object.text();if(utf8ByteLength(text)>maxBytes)return response(`Stored ${errorLabel.toLowerCase()} is invalid`,{status:422});let parsed;try{parsed=JSON.parse(text);}catch{return response(`Stored ${errorLabel.toLowerCase()} is invalid`,{status:422});}if(!validator(parsed))return response(`Stored ${errorLabel.toLowerCase()} is invalid`,{status:422});return response(text,{headers:{'Content-Type':'application/json; charset=utf-8',...(etag?{ETag:etag}:{})}});}if(request.method!=='PUT')return response('Method not allowed',{status:405});const condition=await requiredWriteCondition(request,env,route.key);if(!condition)return response('Precondition required',{status:428});const contentType=(request.headers.get('Content-Type')||'').split(';')[0].trim().toLowerCase();if(contentType!=='application/json')return response('JSON content required',{status:415});const body=await readBoundedText(request,maxBytes);if(body.tooLarge)return response(`${errorLabel} exceeds ${Math.round(maxBytes/1024/1024)} MB`,{status:413});let parsed;try{parsed=JSON.parse(body.text);}catch{return response('Invalid JSON',{status:400});}if(!validator(parsed))return response(`Invalid ${errorLabel.toLowerCase()}`,{status:400});const stored=await env.BUCKET.put(route.key,body.text,{onlyIf:condition,httpMetadata:{contentType:'application/json; charset=utf-8',cacheControl:'private, no-store'}});if(stored===null)return response('Document changed; reread and retry',{status:412});const etag=objectEtag(stored);return response('OK',{headers:etag?{ETag:etag}:{}});}
async function handleListeningObject(request,env,route){if(route.kind==='manifest')return handleListeningJson(request,env,route,MAX_LISTENING_MANIFEST_BYTES,listeningManifestIsValid,'Listening manifest');if(route.kind==='metadata')return handleListeningJson(request,env,route,MAX_SPOTIFY_METADATA_BYTES,spotifyListeningMetadataIsValid,'Spotify listening metadata');if(route.kind==='activity')return handleListeningJson(request,env,route,MAX_LISTENING_BAND_ACTIVITY_BYTES,listeningBandActivityIsValid,'Listening band activity',{validateRead:true});if(route.kind==='identities'){if(request.method==='PUT'&&!writeCondition(request))return response('Precondition required',{status:428});return handleListeningJson(request,env,route,MAX_TRACK_IDENTITIES_BYTES,trackIdentitiesIsValid,'Track identities');}if(route.kind==='catalogue'){if(request.method==='PUT'&&!writeCondition(request))return response('Precondition required',{status:428});return handleListeningJson(request,env,route,MAX_MUSICBRAINZ_CATALOGUE_BYTES,musicbrainzCatalogueIsValid,'MusicBrainz catalogue');}if(request.method==='GET'){const object=await env.BUCKET.get(route.key);if(!object)return response('Not found',{status:404});const etag=objectEtag(object);return response(object.body,{headers:{'Content-Type':'application/gzip',...(etag?{ETag:etag}:{})}});}if(request.method!=='PUT')return response('Method not allowed',{status:405});const condition=await requiredWriteCondition(request,env,route.key);if(!condition)return response('Precondition required',{status:428});const contentType=(request.headers.get('Content-Type')||'').split(';')[0].trim().toLowerCase();if(contentType!=='application/gzip'&&contentType!=='application/octet-stream')return response('Gzip content required',{status:415});const body=await readBoundedBytes(request,MAX_LISTENING_ARCHIVE_BYTES);if(body.tooLarge)return response('Listening archive exceeds 100 MB',{status:413});const bytes=new Uint8Array(body.bytes);if(bytes.length<2||bytes[0]!==0x1f||bytes[1]!==0x8b)return response('Invalid gzip archive',{status:400});const stored=await env.BUCKET.put(route.key,body.bytes,{onlyIf:condition,httpMetadata:{contentType:'application/gzip',cacheControl:'private, no-store'}});if(stored===null)return response('Archive already exists or changed',{status:412});const etag=objectEtag(stored);return response('OK',{headers:etag?{ETag:etag}:{}});}
export default {
  async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{headers:response(null).headers});const url=new URL(request.url);if(url.pathname===MUSICBRAINZ_RELEASE_CONTEXT_PATH){const role=authorizationRole(request,env);if(!role)return response('Unauthorized',{status:401});if(role!=='browser')return response('Forbidden',{status:403});return handleMusicbrainzReleaseContext(request);}if(url.pathname==='/qa-smoke'){if(request.method!=='GET')return response('Method not allowed',{status:405});const role=authorizationRole(request,env);if(role==='data-maintenance')return response('Forbidden',{status:403});if(!isReadOnlyAuthorized(request,env))return response('Unauthorized',{status:401});return qaSmoke(env);}const ticket=ticketRoute(url.pathname);const listening=listeningRoute(url.pathname);const filename=url.pathname.replace(/^\//,'');if(!ticket&&!listening&&!ALLOWED_FILES.has(filename))return response('Not found',{status:404});const role=authorizationRole(request,env);if(!role)return response('Unauthorized',{status:401});if(filename===DISCOVER_RECOMMENDATIONS_FILE&&role!=='browser')return response('Forbidden',{status:403});if(role==='data-maintenance'){if(ticket)return response('Forbidden',{status:403});if(listening&&!maintenanceListeningAllowed(listening,request.method))return response('Forbidden',{status:403});if(!listening&&!maintenanceJsonAllowed(filename,request.method))return response('Forbidden',{status:403});}if(filename==='venues.json'&&request.method==='PUT'&&role!=='data-maintenance')return response('Forbidden',{status:403});if(ticket&&role==='automation')return response('Forbidden',{status:403});if(listening?.kind==='identities'&&request.method==='PUT'&&role!=='data-maintenance')return response('Forbidden',{status:403});if(listening?.kind==='catalogue'&&role!=='data-maintenance')return response('Forbidden',{status:403});if(listening&&role!=='browser'&&role!=='legacy'&&role!=='data-maintenance'&&!(role==='automation'&&listening.kind==='activity'&&request.method==='GET'))return response('Forbidden',{status:403});if(ticket)return handleTicketFile(request,env,ticket);if(listening)return handleListeningObject(request,env,listening);return handleJsonFile(request,env,filename);}
};