const SPOTIFY_METADATA_ID = /^[A-Za-z0-9]{1,64}$/;
const SPOTIFY_ISRC = /^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$/i;
const MAX_SPOTIFY_METADATA_RECORDS = 100000;
function spotifyMetadataDateIsValid(value){return value==null||(typeof value==='string'&&Number.isFinite(Date.parse(value)));}
function spotifyMetadataHttpsUrlIsValid(value){if(value==null)return true;if(typeof value!=='string'||!value)return false;try{return new URL(value).protocol==='https:';}catch{return false;}}
function spotifyMetadataSpotifyUrlIsValid(value,kind,id){if(typeof value!=='string')return false;try{const url=new URL(value);return url.protocol==='https:'&&url.hostname==='open.spotify.com'&&url.pathname===`/${kind}/${id}`;}catch{return false;}}
function spotifyListeningMetadataRecordIsValid(key,record){if(!SPOTIFY_METADATA_ID.test(String(key||''))||!record||typeof record!=='object'||Array.isArray(record))return false;if(record.spotifyTrackId!==key)return false;if(!spotifyMetadataSpotifyUrlIsValid(record.spotifyTrackUrl,'track',key))return false;if(record.spotifyAlbumId!=null){if(!SPOTIFY_METADATA_ID.test(String(record.spotifyAlbumId)))return false;if(!spotifyMetadataSpotifyUrlIsValid(record.spotifyAlbumUrl,'album',record.spotifyAlbumId))return false;}else if(record.spotifyAlbumUrl!=null)return false;if(!spotifyMetadataHttpsUrlIsValid(record.artworkUrl))return false;if(!spotifyMetadataDateIsValid(record.fetchedAt))return false;if(record.source!=='spotify_exact_track_id')return false;if(record.spotifyArtistIds!=null){if(!Array.isArray(record.spotifyArtistIds)||record.spotifyArtistIds.length>20||record.spotifyArtistIds.some((id)=>!SPOTIFY_METADATA_ID.test(String(id||''))))return false;}if(record.isrc!=null&&!SPOTIFY_ISRC.test(String(record.isrc)))return false;return true;}
function spotifyListeningMetadataIsValid(value){if(!value||typeof value!=='object'||Array.isArray(value))return false;if(value.kind!=='livevault-spotify-listening-metadata'||value.schemaVersion!==1)return false;if(!spotifyMetadataDateIsValid(value.updatedAt))return false;if(!value.records||typeof value.records!=='object'||Array.isArray(value.records))return false;const entries=Object.entries(value.records);if(entries.length>MAX_SPOTIFY_METADATA_RECORDS)return false;return entries.every(([key,record])=>spotifyListeningMetadataRecordIsValid(key,record));}

const ALLOWED_FILES = new Set(['bands.json','concerts.json','news.json','apiUsage.json']);
const JSON_ROOT_TYPES = {'bands.json':'array','concerts.json':'array','news.json':'array','apiUsage.json':'object'};
const MAX_JSON_BYTES = 10 * 1024 * 1024;
const MAX_LISTENING_MANIFEST_BYTES = 1024 * 1024;
const MAX_LISTENING_ARCHIVE_BYTES = 100 * 1024 * 1024;
const MAX_SPOTIFY_METADATA_BYTES = 25 * 1024 * 1024;
const MAX_TRACK_IDENTITIES_BYTES = 25 * 1024 * 1024;
const MAX_WEATHER_BYTES = 5 * 1024 * 1024;
const MAX_TICKET_PDF_BYTES = 10 * 1024 * 1024;
const SAFE_ID = /^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/;
const MUSICBRAINZ_MBID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const TRACK_KEY = /^(?:spotify:[A-Za-z0-9]{1,64}|listenbrainz:[a-f0-9]{64})$/;
const TRACK_IDENTITY_STATUSES = new Set(['complete','unresolved','ambiguous','no_match','retry','review']);
const MUSICBRAINZ_RELEASE_CONTEXT_PATH = '/musicbrainz/release-context';
const MUSICBRAINZ_ROOT = 'https://musicbrainz.org/ws/2';
const MUSICBRAINZ_USER_AGENT = 'BANDMARKR/104 (https://github.com/mstpln/concert-tracker-mobile)';
const MUSICBRAINZ_TIMEOUT_MS = 10000;
const LISTENING_MANIFEST_PATH = 'listening/manifest.json';
const SPOTIFY_METADATA_PATH = 'listening/spotify-metadata.json';
const TRACK_IDENTITIES_PATH = 'listening/track-identities.json';
const WEATHER_PATH = 'weather.json';
const SPOTIFY_ARCHIVE_PATTERN = /^listening\/spotify-history\/([a-f0-9]{64})\.json\.gz$/;
const LISTENBRAINZ_ARCHIVE_PATTERN = /^listening\/listenbrainz\/(\d{4}-(?:0[1-9]|1[0-2]))\/([a-f0-9]{64})\.json\.gz$/;
function corsHeaders(){return {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, PUT, DELETE, OPTIONS','Access-Control-Allow-Headers':'Authorization, Content-Type, If-Match, If-None-Match','Access-Control-Expose-Headers':'ETag'};}
function response(body,init={}){return new Response(body,{...init,headers:{...corsHeaders(),'Cache-Control':'private, no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff',...(init.headers||{})}});}
function bearerToken(request){return(request.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');}
function authorizationRole(request,env){const token=bearerToken(request);if(!token)return null;if(env.BROWSER_TOKEN&&token===env.BROWSER_TOKEN)return'browser';if(env.AUTOMATION_TOKEN&&token===env.AUTOMATION_TOKEN)return'automation';if(env.DATA_MAINTENANCE_TOKEN&&token===env.DATA_MAINTENANCE_TOKEN)return'data-maintenance';if(env.API_TOKEN&&token===env.API_TOKEN)return'legacy';return null;}
function isReadOnlyAuthorized(request,env){const token=bearerToken(request);return!!token&&(!!authorizationRole(request,env)||(!!env.READ_ONLY_TOKEN&&token===env.READ_ONLY_TOKEN));}
function jsonRootIsValid(filename,value){return JSON_ROOT_TYPES[filename]==='array'?Array.isArray(value):!!value&&typeof value==='object'&&!Array.isArray(value);}
function archiveEntryIsValid(entry,source){if(!entry||typeof entry!=='object'||Array.isArray(entry))return false;if(entry.source!==source)return false;const pattern=source==='spotify_import'?SPOTIFY_ARCHIVE_PATTERN:LISTENBRAINZ_ARCHIVE_PATTERN;if(!pattern.test(String(entry.path||'')))return false;if(!/^[a-f0-9]{64}$/.test(String(entry.sha256||'')))return false;if(entry.contentEncoding!=='gzip')return false;if(!Number.isInteger(entry.eventCount)||entry.eventCount<0||entry.eventCount>10000000)return false;return true;}
function listeningManifestIsValid(value){if(!value||typeof value!=='object'||Array.isArray(value))return false;if(value.kind!=='livevault-listening-vault'||value.schemaVersion!==1)return false;if(!archiveEntryIsValid(value.archive,'spotify_import'))return false;if(value.incrementals!=null){if(!Array.isArray(value.incrementals)||value.incrementals.length>10000)return false;for(const item of value.incrementals){if(!archiveEntryIsValid(item,'listenbrainz'))return false;if(!/^\d{4}-(?:0[1-9]|1[0-2])$/.test(String(item.month||'')))return false;}}return true;}
function trackIdentityEvidenceIsValid(value){return!!value&&typeof value==='object'&&!Array.isArray(value)&&typeof value.source==='string'&&value.source.length>0&&value.source.length<=64&&spotifyMetadataDateIsValid(value.observedAt);}
function trackIdentityRecordIsValid(key,record){if(!TRACK_KEY.test(String(key||''))||!record||typeof record!=='object'||Array.isArray(record)||record.trackKey!==key||!SAFE_ID.test(String(record.bandId||'')))return false;if(!TRACK_IDENTITY_STATUSES.has(record.status))return false;if(record.musicbrainzRecordingMbid!=null&&!MUSICBRAINZ_MBID.test(String(record.musicbrainzRecordingMbid)))return false;if(record.musicbrainzArtistMbids!=null){if(!Array.isArray(record.musicbrainzArtistMbids)||record.musicbrainzArtistMbids.length>20||record.musicbrainzArtistMbids.some((id)=>!MUSICBRAINZ_MBID.test(String(id||''))))return false;}if(record.evidence!=null){if(!Array.isArray(record.evidence)||record.evidence.length>20||record.evidence.some((item)=>!trackIdentityEvidenceIsValid(item)))return false;}if(!spotifyMetadataDateIsValid(record.verifiedAt)||!spotifyMetadataDateIsValid(record.nextEligibleCheckAt))return false;return true;}
function trackIdentitiesIsValid(value){if(!value||typeof value!=='object'||Array.isArray(value)||value.kind!=='bandmarkr-listening-track-identities'||value.schemaVersion!==1||!spotifyMetadataDateIsValid(value.updatedAt)||!value.records||typeof value.records!=='object'||Array.isArray(value.records))return false;const entries=Object.entries(value.records);return entries.length<=100000&&entries.every(([key,record])=>trackIdentityRecordIsValid(key,record));}
function weatherCoordinatesAreValid(value){if(value==null)return true;if(!value||typeof value!=='object'||Array.isArray(value))return false;const lat=Number(value.latitude);const lon=Number(value.longitude);return Number.isFinite(lat)&&lat>=-90&&lat<=90&&Number.isFinite(lon)&&lon>=-180&&lon<=180;}
function weatherRecordIsValid(key,record){if(!SAFE_ID.test(String(key||''))||!record||typeof record!=='object'||Array.isArray(record)||record.concertId!==key||record.source!=='open-meteo')return false;if(!spotifyMetadataDateIsValid(record.fetchedAt)||!spotifyMetadataDateIsValid(record.nextEligibleCheckAt)||!spotifyMetadataDateIsValid(record.locationResolvedAt)||!weatherCoordinatesAreValid(record.coordinates))return false;if(record.locationFingerprint!=null&&!/^[a-f0-9]{64}$/.test(String(record.locationFingerprint)))return false;if(record.forecast!=null&&(!record.forecast||typeof record.forecast!=='object'||Array.isArray(record.forecast)))return false;return true;}
function weatherIsValid(value){if(!value||typeof value!=='object'||Array.isArray(value)||value.kind!=='bandmarkr-concert-weather'||value.schemaVersion!==1||!spotifyMetadataDateIsValid(value.updatedAt)||!value.records||typeof value.records!=='object'||Array.isArray(value.records))return false;const entries=Object.entries(value.records);return entries.length<=100000&&entries.every(([key,record])=>weatherRecordIsValid(key,record));}
function utf8ByteLength(text){let bytes=0;for(let index=0;index<text.length;index+=1){const code=text.charCodeAt(index);if(code<0x80)bytes+=1;else if(code<0x800)bytes+=2;else if(code>=0xd800&&code<=0xdbff&&index+1<text.length&&text.charCodeAt(index+1)>=0xdc00&&text.charCodeAt(index+1)<=0xdfff){bytes+=4;index+=1;}else bytes+=3;}return bytes;}
async function readBoundedText(request,maxBytes){const declared=Number(request.headers.get('Content-Length'));if(Number.isFinite(declared)&&declared>maxBytes)return{tooLarge:true};const text=await request.text();return utf8ByteLength(text)>maxBytes?{tooLarge:true}:{text};}
async function readBoundedBytes(request,maxBytes){const declared=Number(request.headers.get('Content-Length'));if(Number.isFinite(declared)&&declared>maxBytes)return{tooLarge:true};const bytes=await request.arrayBuffer();return bytes.byteLength>maxBytes?{tooLarge:true}:{bytes};}
function objectEtag(object){if(!object)return null;if(object.httpEtag)return object.httpEtag;return object.etag?`"${String(object.etag).replace(/^"|"$/g,'')}"`:null;}
function bareEtag(value){return String(value||'').trim().replace(/^W\//,'').replace(/^"|"$/g,'');}
function writeCondition(request){const ifMatch=request.headers.get('If-Match');const ifNone=request.headers.get('If-None-Match');if(ifMatch)return{etagMatches:bareEtag(ifMatch)};if(ifNone==='*')return{etagDoesNotMatch:'*'};return null;}
async function requiredWriteCondition(request,env,key){const condition=writeCondition(request);if(condition)return condition;const existing=typeof env.BUCKET.head==='function'?await env.BUCKET.head(key):await env.BUCKET.get(key);return existing?null:{etagDoesNotMatch:'*'};}
async function qaSmoke(env){const files={};let healthy=true;for(const[filename,type]of Object.entries(JSON_ROOT_TYPES)){try{const object=await env.BUCKET.get(filename);if(!object){files[filename]={ok:false,reason:'missing'};healthy=false;continue;}const value=JSON.parse(await object.text());const valid=type==='array'?Array.isArray(value):!!value&&typeof value==='object'&&!Array.isArray(value);files[filename]={ok:valid,type,count:Array.isArray(value)?value.length:null};if(!valid)healthy=false;}catch{files[filename]={ok:false,reason:'invalid'};healthy=false;}}return response(JSON.stringify({ok:healthy,files}),{status:healthy?200:503,headers:{'Content-Type':'application/json; charset=utf-8'}});}
function ticketRoute(pathname){const match=pathname.match(/^\/ticket-files\/([A-Za-z0-9][A-Za-z0-9_-]{0,127})\/([A-Za-z0-9][A-Za-z0-9_-]{0,127})\.pdf$/);return match&&SAFE_ID.test(match[1])&&SAFE_ID.test(match[2])?{concertId:match[1],ticketId:match[2]}:null;}
function listeningRoute(pathname){const key=pathname.replace(/^\//,'');if(key===LISTENING_MANIFEST_PATH)return{kind:'manifest',key};if(key===SPOTIFY_METADATA_PATH)return{kind:'metadata',key};if(key===TRACK_IDENTITIES_PATH)return{kind:'identities',key};if(SPOTIFY_ARCHIVE_PATTERN.test(key))return{kind:'archive',key};if(LISTENBRAINZ_ARCHIVE_PATTERN.test(key))return{kind:'incremental',key};return null;}
function musicbrainzReleaseMbid(value){const text=String(value||'').trim().toLowerCase();return MUSICBRAINZ_MBID.test(text)?text:null;}
async function handleMusicbrainzReleaseContext(request,fetchImpl=fetch){if(request.method!=='GET')return response('Method not allowed',{status:405});const url=new URL(request.url);const releaseMbid=musicbrainzReleaseMbid(url.searchParams.get('release_mbid'));if(!releaseMbid)return response('Invalid release MBID',{status:400});const upstream=new URL(`${MUSICBRAINZ_ROOT}/release/${encodeURIComponent(releaseMbid)}`);upstream.searchParams.set('inc','release-groups');upstream.searchParams.set('fmt','json');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),MUSICBRAINZ_TIMEOUT_MS);let providerResponse;try{providerResponse=await fetchImpl(upstream,{headers:{Accept:'application/json','User-Agent':MUSICBRAINZ_USER_AGENT},signal:controller.signal});}catch(error){return response(error?.name==='AbortError'?'MusicBrainz request timed out':'MusicBrainz request failed',{status:502});}finally{clearTimeout(timer);}if(providerResponse.status===404)return response('Not found',{status:404});if(providerResponse.status===429||providerResponse.status===503)return response('MusicBrainz rate limited',{status:503});if(!providerResponse.ok)return response('MusicBrainz request failed',{status:502});let payload;try{payload=await providerResponse.json();}catch{return response('Invalid MusicBrainz response',{status:502});}const returnedReleaseMbid=musicbrainzReleaseMbid(payload?.id);const releaseGroupMbid=musicbrainzReleaseMbid(payload?.['release-group']?.id||payload?.release_group?.id);if(returnedReleaseMbid!==releaseMbid||!releaseGroupMbid)return response('Invalid MusicBrainz response',{status:502});return response(JSON.stringify({releaseMbid,releaseGroupMbid}),{headers:{'Content-Type':'application/json; charset=utf-8'}});}
async function handleTicketFile(request,env,route){const key=`ticket-files/${route.concertId}/${route.ticketId}.pdf`;if(request.method==='GET'){const object=await env.BUCKET.get(key);if(!object)return response('Not found',{status:404});return response(object.body,{headers:{'Content-Type':'application/pdf','Content-Disposition':'inline'}});}if(request.method==='DELETE'){await env.BUCKET.delete(key);return response('OK');}if(request.method!=='PUT')return response('Method not allowed',{status:405});if((request.headers.get('Content-Type')||'').split(';')[0].trim().toLowerCase()!=='application/pdf')return response('PDF content required',{status:400});const body=await readBoundedBytes(request,MAX_TICKET_PDF_BYTES);if(body.tooLarge)return response('PDF exceeds 10 MB',{status:413});const bytes=new Uint8Array(body.bytes);if(bytes.length<5||new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')return response('Invalid PDF',{status:400});await env.BUCKET.put(key,body.bytes,{httpMetadata:{contentType:'application/pdf',contentDisposition:'inline',cacheControl:'private, no-store'}});return response('OK');}
async function handleJsonFile(request,env,filename){if(request.method==='GET'){const object=await env.BUCKET.get(filename);if(!object)return response('Not found',{status:404});const etag=objectEtag(object);return response(object.body,{headers:{'Content-Type':'application/json; charset=utf-8',...(etag?{ETag:etag}:{})}});}if(request.method!=='PUT')return response('Method not allowed',{status:405});const condition=await requiredWriteCondition(request,env,filename);if(!condition)return response('Precondition required',{status:428});const contentType=(request.headers.get('Content-Type')||'').split(';')[0].trim().toLowerCase();if(contentType!=='application/json')return response('JSON content required',{status:415});const body=await readBoundedText(request,MAX_JSON_BYTES);if(body.tooLarge)return response('JSON exceeds 10 MB',{status:413});let parsed;try{parsed=JSON.parse(body.text);}catch{return response('Invalid JSON',{status:400});}if(!jsonRootIsValid(filename,parsed))return response('Invalid JSON document type',{status:400});const stored=await env.BUCKET.put(filename,body.text,{onlyIf:condition,httpMetadata:{contentType:'application/json; charset=utf-8',cacheControl:'private, no-store'}});if(stored===null)return response('Document changed; reread and retry',{status:412});const etag=objectEtag(stored);return response('OK',{headers:etag?{ETag:etag}:{}});}
async function handlePrivateJson(request,env,key,maxBytes,validator,errorLabel){if(request.method==='GET'){const object=await env.BUCKET.get(key);if(!object)return response('Not found',{status:404});const etag=objectEtag(object);return response(object.body,{headers:{'Content-Type':'application/json; charset=utf-8',...(etag?{ETag:etag}:{})}});}if(request.method!=='PUT')return response('Method not allowed',{status:405});const condition=await requiredWriteCondition(request,env,key);if(!condition)return response('Precondition required',{status:428});const contentType=(request.headers.get('Content-Type')||'').split(';')[0].trim().toLowerCase();if(contentType!=='application/json')return response('JSON content required',{status:415});const body=await readBoundedText(request,maxBytes);if(body.tooLarge)return response(`${errorLabel} exceeds ${Math.round(maxBytes/1024/1024)} MB`,{status:413});let parsed;try{parsed=JSON.parse(body.text);}catch{return response('Invalid JSON',{status:400});}if(!validator(parsed))return response(`Invalid ${errorLabel.toLowerCase()}`,{status:400});const stored=await env.BUCKET.put(key,body.text,{onlyIf:condition,httpMetadata:{contentType:'application/json; charset=utf-8',cacheControl:'private, no-store'}});if(stored===null)return response('Document changed; reread and retry',{status:412});const etag=objectEtag(stored);return response('OK',{headers:etag?{ETag:etag}:{}});}
async function handleListeningObject(request,env,route){if(route.kind==='manifest')return handlePrivateJson(request,env,route.key,MAX_LISTENING_MANIFEST_BYTES,listeningManifestIsValid,'Listening manifest');if(route.kind==='metadata')return handlePrivateJson(request,env,route.key,MAX_SPOTIFY_METADATA_BYTES,spotifyListeningMetadataIsValid,'Spotify listening metadata');if(route.kind==='identities')return handlePrivateJson(request,env,route.key,MAX_TRACK_IDENTITIES_BYTES,trackIdentitiesIsValid,'Listening track identities');if(request.method==='GET'){const object=await env.BUCKET.get(route.key);if(!object)return response('Not found',{status:404});const etag=objectEtag(object);return response(object.body,{headers:{'Content-Type':'application/gzip',...(etag?{ETag:etag}:{})}});}if(request.method!=='PUT')return response('Method not allowed',{status:405});const condition=await requiredWriteCondition(request,env,route.key);if(!condition)return response('Precondition required',{status:428});const contentType=(request.headers.get('Content-Type')||'').split(';')[0].trim().toLowerCase();if(contentType!=='application/gzip'&&contentType!=='application/octet-stream')return response('Gzip content required',{status:415});const body=await readBoundedBytes(request,MAX_LISTENING_ARCHIVE_BYTES);if(body.tooLarge)return response('Listening archive exceeds 100 MB',{status:413});const bytes=new Uint8Array(body.bytes);if(bytes.length<2||bytes[0]!==0x1f||bytes[1]!==0x8b)return response('Invalid gzip archive',{status:400});const stored=await env.BUCKET.put(route.key,body.bytes,{onlyIf:condition,httpMetadata:{contentType:'application/gzip',cacheControl:'private, no-store'}});if(stored===null)return response('Archive already exists or changed',{status:412});const etag=objectEtag(stored);return response('OK',{headers:etag?{ETag:etag}:{}});}
function dataMaintenanceRootAllowed(filename,method){if(method==='GET')return filename==='bands.json'||filename==='concerts.json'||filename==='apiUsage.json';if(method==='PUT')return filename==='apiUsage.json';return false;}
function dataMaintenanceListeningAllowed(route,method){if(method==='GET')return true;if(method!=='PUT')return false;return route.kind==='metadata'||route.kind==='identities';}
export default {
  async fetch(request,env){
    if(request.method==='OPTIONS')return new Response(null,{headers:response(null).headers});
    const url=new URL(request.url);
    if(url.pathname===MUSICBRAINZ_RELEASE_CONTEXT_PATH){const role=authorizationRole(request,env);if(!role)return response('Unauthorized',{status:401});if(role!=='browser')return response('Forbidden',{status:403});return handleMusicbrainzReleaseContext(request);}
    if(url.pathname==='/qa-smoke'){if(request.method!=='GET')return response('Method not allowed',{status:405});if(!isReadOnlyAuthorized(request,env))return response('Unauthorized',{status:401});return qaSmoke(env);}
    const ticket=ticketRoute(url.pathname);
    const listening=listeningRoute(url.pathname);
    const filename=url.pathname.replace(/^\//,'');
    const weather=filename===WEATHER_PATH;
    if(!ticket&&!listening&&!weather&&!ALLOWED_FILES.has(filename))return response('Not found',{status:404});
    const role=authorizationRole(request,env);
    if(!role)return response('Unauthorized',{status:401});
    if(role==='data-maintenance'){
      if(ticket)return response('Forbidden',{status:403});
      if(weather){if(request.method!=='GET'&&request.method!=='PUT')return response('Forbidden',{status:403});return handlePrivateJson(request,env,WEATHER_PATH,MAX_WEATHER_BYTES,weatherIsValid,'Weather document');}
      if(listening){if(!dataMaintenanceListeningAllowed(listening,request.method))return response('Forbidden',{status:403});return handleListeningObject(request,env,listening);}
      if(!dataMaintenanceRootAllowed(filename,request.method))return response('Forbidden',{status:403});
      return handleJsonFile(request,env,filename);
    }
    if(ticket&&role==='automation')return response('Forbidden',{status:403});
    if(weather){if(role!=='browser'&&role!=='legacy')return response('Forbidden',{status:403});if(request.method!=='GET')return response('Forbidden',{status:403});return handlePrivateJson(request,env,WEATHER_PATH,MAX_WEATHER_BYTES,weatherIsValid,'Weather document');}
    if(listening){if(role!=='browser'&&role!=='legacy')return response('Forbidden',{status:403});if(listening.kind==='identities'&&request.method!=='GET')return response('Forbidden',{status:403});return handleListeningObject(request,env,listening);}
    if(ticket)return handleTicketFile(request,env,ticket);
    return handleJsonFile(request,env,filename);
  }
};
