'use strict';
const SPOTIFY_TRACK_ID=/^[A-Za-z0-9]{1,64}$/;const PATCH=Symbol.for('bandmarkr.v136.nonPlaylistTrackLinkReuse');
function normalize(v){return String(v||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('en').replace(/[^\p{L}\p{N}]+/gu,' ').trim().replace(/\s+/g,' ');}
function spotifyTrackIdFromUrl(v){if(typeof v!=='string'||!v.trim())return null;try{const u=new URL(v);if(u.protocol!=='https:'||u.hostname!=='open.spotify.com')return null;const m=u.pathname.match(/^\/track\/([A-Za-z0-9]{1,64})\/?$/);return m?m[1]:null;}catch{return null;}}
function spotifyUrl(id){id=String(id||'').trim();return SPOTIFY_TRACK_ID.test(id)?`https://open.spotify.com/track/${id}`:null;}
function relationUrl(r){return typeof r==='string'?r:r?.url?.resource||r?.target||r?.url||null;}
function uniqueSpotifyRelation(rs){const ids=[...new Set((Array.isArray(rs)?rs:[]).map(relationUrl).map(spotifyTrackIdFromUrl).filter(Boolean))];return ids.length===1?spotifyUrl(ids[0]):null;}
function evidenceSpotifyUrl(e={}){const id=String(e.spotifyTrackId||'').trim();if(SPOTIFY_TRACK_ID.test(id))return spotifyUrl(id);const direct=spotifyTrackIdFromUrl(e.spotifyUrl||e.spotifyTrackUrl);if(direct)return spotifyUrl(direct);return uniqueSpotifyRelation(e.listenbrainzUrlRels||e.listenbrainzUrlRelations)||uniqueSpotifyRelation(e.musicbrainzUrlRels||e.musicbrainzUrlRelations);}
function identityKey({bandId,spotifyArtistId,artistName,recordingTitle,title}={}){const recording=normalize(recordingTitle||title);if(!recording)return null;const artist=String(spotifyArtistId||'').trim()?`spotify:${String(spotifyArtistId).trim()}`:String(bandId||'').trim()?`band:${String(bandId).trim()}`:normalize(artistName)?`name:${normalize(artistName)}`:null;return artist?`${artist}\n${recording}`:null;}
function createResolver(initial=[]){const links=new Map(),conflicts=new Set();function add(e={}){const k=identityKey(e),u=evidenceSpotifyUrl(e);if(!k||!u||conflicts.has(k))return false;const p=links.get(k);if(p&&p!==u){links.delete(k);conflicts.add(k);return false;}links.set(k,u);return true;}function resolve(q={}){const k=identityKey(q);return k&&!conflicts.has(k)?links.get(k)||null:null;}for(const e of initial||[])add(e);return{add,resolve,size:()=>links.size,hasConflict:q=>conflicts.has(identityKey(q))};}
function trustedSpotifyArtistId(b){const r=b?.musicbrainz?.spotify;return['confirmed','manual_confirmed'].includes(r?.status)&&SPOTIFY_TRACK_ID.test(String(r?.id||''))?r.id:null;}
function songEvidence(song,artist={}){if(!song||typeof song!=='object'||Array.isArray(song))return null;const recordingTitle=song.recordingTitle||song.name||song.title;if(!normalize(recordingTitle))return null;return{bandId:artist.bandId||song.bandId||song.localBandId||null,spotifyArtistId:artist.spotifyArtistId||song.spotifyArtistId||null,artistName:artist.artistName||song.artistCreditName||song.bandName||null,recordingTitle,spotifyTrackId:song.spotifyTrackId||null,spotifyUrl:song.spotifyUrl||song.spotifyTrackUrl||null,listenbrainzUrlRels:song.listenbrainzUrlRels||song.listenbrainzUrlRelations||null,musicbrainzUrlRels:song.musicbrainzUrlRels||song.musicbrainzUrlRelations||null};}
function collectConcertEvidence(concerts=[],bands=[]){const byId=new Map((bands||[]).map(b=>[b?.id,b])),out=[];for(const c of concerts||[]){const b=byId.get(c?.bandId),artist={bandId:c?.bandId||null,spotifyArtistId:trustedSpotifyArtistId(b),artistName:b?.name||c?.bandName||null};for(const s of [...(c?.setlist?.songs||[]),...(c?.predictedSetlist?.songs||[])]){const row=songEvidence(s,artist);if(row&&evidenceSpotifyUrl(row))out.push(row);}}return out;}
function collectListeningEvidence(events=[],{bands=[]}={}){const byId=new Map((bands||[]).map(b=>[b?.id,b])),out=[];for(const e of events||[]){const bandId=e?.localBandId||e?.bandId||null,b=byId.get(bandId),row=songEvidence(e,{bandId,spotifyArtistId:trustedSpotifyArtistId(b),artistName:b?.name||e?.artistCreditName||null});if(row&&evidenceSpotifyUrl(row))out.push(row);}return out;}
const sharedResolver=createResolver();let providerNeutralLookup=null;
function seedEvidence(rows=[]){let added=0;for(const row of rows||[])if(sharedResolver.add(row))added++;return added;}
function setProviderNeutralLookup(fn){providerNeutralLookup=typeof fn==='function'?fn:null;}
function installSpotifyNonPlaylistReuse(spotify){if(!spotify||typeof spotify.resolveSongLinks!=='function'||typeof spotify.searchTrackOutcome!=='function')throw new Error('Non-playlist reuse requires Spotify song-link helpers.');if(spotify[PATCH])return false;Object.defineProperty(spotify,PATCH,{value:true,enumerable:false});const original=spotify.resolveSongLinks;spotify.resolveSongLinks=async function(songs,bandName,usage,options={}){const artist={bandId:options.bandId||null,spotifyArtistId:options.spotifyArtistId||null,artistName:bandName};seedEvidence(Array.isArray(options.evidence)?options.evidence:[]);for(const song of songs||[]){const row=songEvidence(song,artist);if(row)sharedResolver.add(row);}const providerSearch=typeof options.search==='function'?options.search:spotify.searchTrackOutcome;const search=async(title,currentBandName,currentUsage,searchOptions={})=>{const query={bandId:searchOptions.bandId||artist.bandId,spotifyArtistId:searchOptions.spotifyArtistId||artist.spotifyArtistId,artistName:currentBandName,recordingTitle:title};const known=sharedResolver.resolve(query);if(known)return{kind:'ok',url:known,reused:true};if(providerNeutralLookup){const neutral=await providerNeutralLookup({...query,usage:currentUsage});if(neutral?.kind==='ok'&&neutral.url){sharedResolver.add({...query,spotifyUrl:neutral.url});return{...neutral,reused:true};}if(neutral?.kind==='error'||neutral?.kind==='skipped')return neutral;}const outcome=await providerSearch(title,currentBandName,currentUsage,searchOptions);if(outcome?.kind==='ok'&&outcome.url)sharedResolver.add({...query,spotifyUrl:outcome.url});return outcome;};return original(songs,bandName,usage,{...options,search});};return true;}
module.exports={normalize,spotifyTrackIdFromUrl,spotifyUrl,uniqueSpotifyRelation,evidenceSpotifyUrl,identityKey,createResolver,trustedSpotifyArtistId,songEvidence,collectConcertEvidence,collectListeningEvidence,seedEvidence,setProviderNeutralLookup,installSpotifyNonPlaylistReuse};
