'use strict';
const config = require('./config');
const worker = require('./workerClient');
const { todayIso, thisMonthIso, sleep } = require('./util');

const SPOTIFY_LANES = new Set(['structured_identity', 'artist_image', 'album_artwork', 'predicted_playlist', 'historical_non_playlist', 'other']);
const SPOTIFY_ENDPOINTS = new Set(['token', 'artist_exact', 'artist_search', 'artist_albums', 'track_exact', 'track_search', 'album_exact_tracks', 'other']);
function spotifyDiagnostics() { return { callsByLane: {}, callsByEndpoint: {}, outcomes: {}, circuitEvents: [], circuitStart: null, circuitFinish: null }; }
function freshState() {
  const today = todayIso(), month = thisMonthIso();
  return {
    ticketmaster: { freeTierDailyLimit: config.TICKETMASTER.freeTierDailyLimit, perRunCap: config.TICKETMASTER.perRunCap, dayOfCounts: today, callsToday: 0, callsThisRun: 0 },
    tavily: { freeTierMonthlyLimit: config.TAVILY.freeTierMonthlyLimit, monthlyCap: config.TAVILY.monthlyCap, perRunCap: config.TAVILY.perRunCap, usageCounterEpoch: config.TAVILY.usageCounterEpoch, monthOfCounts: month, callsThisMonth: 0, callsThisRun: 0 },
    groq: { freeTierDailyRequestLimit: config.GROQ.freeTierDailyRequestLimit, freeTierTpmLimit: config.GROQ.freeTierTpmLimit, freeTierTpdLimit: config.GROQ.freeTierTpdLimit, dailyCap: config.GROQ.dailyCap, perRunCap: config.GROQ.perRunCap, safeTpd: config.GROQ.safeTpd, dayOfCounts: today, callsToday: 0, callsThisRun: 0, tokensToday: 0, tokensThisRun: 0 },
    setlistfm: { freeTierDailyLimit: config.SETLISTFM.freeTierDailyLimit, dailyCap: config.SETLISTFM.dailyCap, perRunCap: config.SETLISTFM.perRunCap, dayOfCounts: today, callsToday: 0, callsThisRun: 0 },
    spotify: { dailyCap: config.SPOTIFY.dailyCap, perRunCap: config.SPOTIFY.perRunCap, dayOfCounts: today, callsToday: 0, callsThisRun: 0, diagnostics: spotifyDiagnostics() },
    musicbrainz: { perRunCap: config.MUSICBRAINZ.perRunCap, callsThisRun: 0, lastCallAt: null },
    structuredResearch: { tavilyByReason: {}, groqByCategory: {}, skips: {}, providerFailures: {} },
    rotation: { nextBandIndex: 0 }, lastRun: null, lastMusicbrainzRun: null, lastProviderIdentityRun: null,
  };
}
function safeCounter(value) { const numeric = Number(value); return Number.isFinite(numeric) && numeric >= 0 ? numeric : 0; }
function ensureTavilyUsageState(state, month = thisMonthIso()) { if (!state.tavily) state.tavily = freshState().tavily; if (state.tavily.usageCounterEpoch !== config.TAVILY.usageCounterEpoch) { state.tavily.usageCounterEpoch = config.TAVILY.usageCounterEpoch; state.tavily.monthOfCounts = month; state.tavily.callsThisMonth = 0; } state.tavily.callsThisMonth = safeCounter(state.tavily.callsThisMonth); return state; }
function ensureMusicbrainzState(state) { if (!state.musicbrainz) state.musicbrainz = freshState().musicbrainz; if (!('lastMusicbrainzRun' in state)) state.lastMusicbrainzRun = null; Object.assign(state.musicbrainz, { perRunCap: config.MUSICBRAINZ.perRunCap }); return state; }
function ensureStructuredResearchState(state) { if (!state.structuredResearch || typeof state.structuredResearch !== 'object') state.structuredResearch = freshState().structuredResearch; for (const key of ['tavilyByReason','groqByCategory','skips','providerFailures']) if (!state.structuredResearch[key] || typeof state.structuredResearch[key] !== 'object') state.structuredResearch[key] = {}; return state; }
function ensureSpotifyDiagnostics(state) { if (!state.spotify.diagnostics || typeof state.spotify.diagnostics !== 'object') state.spotify.diagnostics = spotifyDiagnostics(); return state.spotify.diagnostics; }
class UsageTracker {
  constructor(state) { this.state = state; this._groqWindow=[]; this._notes=[]; this._lastTicketmasterCallAt=0; this._lastTavilyCallAt=0; this._lastGroqCallAt=0; this._lastSetlistfmCallAt=0; this._lastSpotifyCallAt=0; this._lastMusicbrainzCallAt=0; this._startedAt=new Date().toISOString(); this._spotifyContext={lane:'other',endpoint:'other'}; }
  static async load() {
    const stored=await worker.readJson('apiUsage.json',null); const state=stored&&typeof stored==='object'?stored:freshState(); const today=todayIso(), month=thisMonthIso();
    if(!state.ticketmaster)state.ticketmaster=freshState().ticketmaster; ensureTavilyUsageState(state,month); if(!state.groq)state.groq=freshState().groq; if(!state.setlistfm)state.setlistfm=freshState().setlistfm; if(!state.spotify)state.spotify=freshState().spotify; ensureMusicbrainzState(state); if(!('lastProviderIdentityRun'in state))state.lastProviderIdentityRun=null; ensureStructuredResearchState(state); if(!state.rotation||typeof state.rotation.nextBandIndex!=='number')state.rotation={nextBandIndex:0};
    Object.assign(state.ticketmaster,{freeTierDailyLimit:config.TICKETMASTER.freeTierDailyLimit,perRunCap:config.TICKETMASTER.perRunCap}); Object.assign(state.tavily,{freeTierMonthlyLimit:config.TAVILY.freeTierMonthlyLimit,monthlyCap:config.TAVILY.monthlyCap,perRunCap:config.TAVILY.perRunCap}); Object.assign(state.groq,{freeTierDailyRequestLimit:config.GROQ.freeTierDailyRequestLimit,freeTierTpmLimit:config.GROQ.freeTierTpmLimit,freeTierTpdLimit:config.GROQ.freeTierTpdLimit,dailyCap:config.GROQ.dailyCap,perRunCap:config.GROQ.perRunCap,safeTpd:config.GROQ.safeTpd}); Object.assign(state.setlistfm,{freeTierDailyLimit:config.SETLISTFM.freeTierDailyLimit,dailyCap:config.SETLISTFM.dailyCap,perRunCap:config.SETLISTFM.perRunCap}); Object.assign(state.spotify,{dailyCap:config.SPOTIFY.dailyCap,perRunCap:config.SPOTIFY.perRunCap});
    if(state.ticketmaster.dayOfCounts!==today){state.ticketmaster.dayOfCounts=today;state.ticketmaster.callsToday=0;} if(state.groq.dayOfCounts!==today){state.groq.dayOfCounts=today;state.groq.callsToday=0;state.groq.tokensToday=0;} if(typeof state.groq.tokensToday!=='number')state.groq.tokensToday=0; if(state.tavily.monthOfCounts!==month){state.tavily.monthOfCounts=month;state.tavily.callsThisMonth=0;} if(state.setlistfm.dayOfCounts!==today){state.setlistfm.dayOfCounts=today;state.setlistfm.callsToday=0;} state.setlistfm.callsToday=safeCounter(state.setlistfm.callsToday); if(state.spotify.dayOfCounts!==today){state.spotify.dayOfCounts=today;state.spotify.callsToday=0;}
    state.ticketmaster.callsThisRun=state.tavily.callsThisRun=state.groq.callsThisRun=state.groq.tokensThisRun=state.setlistfm.callsThisRun=state.spotify.callsThisRun=state.musicbrainz.callsThisRun=0; const priorCircuit=state.spotify.circuit?{status:state.spotify.circuit.status||null,reason:state.spotify.circuit.reason||null}:null; state.spotify.diagnostics=spotifyDiagnostics(); state.spotify.diagnostics.circuitStart=priorCircuit; return new UsageTracker(state);
  }
  note(text){this._notes.push(text);console.log(`[usage] ${text}`);} recordStructured(kind,value){const bucket=this.state.structuredResearch?.[kind];if(bucket&&value)bucket[value]=(bucket[value]||0)+1;}
  canCallTicketmaster(){const t=this.state.ticketmaster;return t.callsThisRun<t.perRunCap&&t.callsToday<t.freeTierDailyLimit*0.5;} async recordTicketmasterCall(){const gap=Date.now()-this._lastTicketmasterCallAt;if(gap<config.TICKETMASTER.minDelayMs)await sleep(config.TICKETMASTER.minDelayMs-gap);this._lastTicketmasterCallAt=Date.now();this.state.ticketmaster.callsThisRun++;this.state.ticketmaster.callsToday++;}
  canCallTavily(){const t=this.state.tavily;return t.callsThisRun<t.perRunCap&&t.callsThisMonth<t.monthlyCap;} async recordTavilyCall(){const gap=Date.now()-this._lastTavilyCallAt;if(gap<config.TAVILY.minDelayMs)await sleep(config.TAVILY.minDelayMs-gap);this._lastTavilyCallAt=Date.now();this.state.tavily.callsThisRun++;this.state.tavily.callsThisMonth++;}
  canCallGroq(estimatedTokens=1500){const g=this.state.groq;if(g.callsThisRun>=g.perRunCap||g.callsToday>=g.dailyCap||g.tokensToday+estimatedTokens>g.safeTpd)return false;const cutoff=Date.now()-60000;this._groqWindow=this._groqWindow.filter(x=>x.at>cutoff);return this._groqWindow.reduce((s,x)=>s+x.tokens,0)+estimatedTokens<=config.GROQ.safeTpm;} async waitForGroqWindow(estimatedTokens=1500){while(!this.canCallGroq(estimatedTokens)){await sleep(1000);}} async recordGroqCall(){const gap=Date.now()-this._lastGroqCallAt;if(gap<config.GROQ.minDelayMs)await sleep(config.GROQ.minDelayMs-gap);this._lastGroqCallAt=Date.now();} recordGroqAttempt(){this.state.groq.callsThisRun++;this.state.groq.callsToday++;} recordGroqTokens(actualTokens){const tokens=Number.isFinite(actualTokens)?actualTokens:1500;this._groqWindow.push({at:Date.now(),tokens});this.state.groq.tokensThisRun+=tokens;this.state.groq.tokensToday+=tokens;}
  canCallSetlistfm(){const s=this.state.setlistfm;return s.callsThisRun<s.perRunCap&&s.callsToday<s.dailyCap;} async recordSetlistfmCall(){const gap=Date.now()-this._lastSetlistfmCallAt;if(gap<config.SETLISTFM.minDelayMs)await sleep(config.SETLISTFM.minDelayMs-gap);this._lastSetlistfmCallAt=Date.now();this.state.setlistfm.callsThisRun++;this.state.setlistfm.callsToday++;}
  canCallSpotify(){const s=this.state.spotify;return s.callsThisRun<s.perRunCap&&s.callsToday<s.dailyCap;}
  setSpotifyContext(lane='other',endpoint='other'){this._spotifyContext={lane:SPOTIFY_LANES.has(lane)?lane:'other',endpoint:SPOTIFY_ENDPOINTS.has(endpoint)?endpoint:'other'};}
  recordSpotifyOutcome(outcome='provider_error'){const d=ensureSpotifyDiagnostics(this.state);const key=['attempted','successful','no_match','skipped','provider_error'].includes(outcome)?outcome:'provider_error';d.outcomes[key]=(d.outcomes[key]||0)+1;}
  recordSpotifyCircuitEvent(event={}){const d=ensureSpotifyDiagnostics(this.state);d.circuitEvents.push({endpoint:SPOTIFY_ENDPOINTS.has(event.endpoint)?event.endpoint:(this._spotifyContext.endpoint||'other'),callOrdinal:safeCounter(event.callOrdinal||this.state.spotify.callsThisRun),status:Number.isFinite(Number(event.status))?Number(event.status):null,reason:typeof event.reason==='string'?event.reason.slice(0,80):null,retryAfter:typeof event.retryAfter==='string'||Number.isFinite(Number(event.retryAfter))?String(event.retryAfter).slice(0,40):null});d.circuitEvents=d.circuitEvents.slice(-10);}
  async recordSpotifyCall(){const gap=Date.now()-this._lastSpotifyCallAt;if(gap<config.SPOTIFY.minDelayMs)await sleep(config.SPOTIFY.minDelayMs-gap);this._lastSpotifyCallAt=Date.now();this.state.spotify.callsThisRun++;this.state.spotify.callsToday++;const d=ensureSpotifyDiagnostics(this.state),lane=this._spotifyContext.lane||'other',endpoint=this._spotifyContext.endpoint||'other';d.callsByLane[lane]=(d.callsByLane[lane]||0)+1;d.callsByEndpoint[endpoint]=(d.callsByEndpoint[endpoint]||0)+1;d.outcomes.attempted=(d.outcomes.attempted||0)+1;}
  canCallMusicbrainz(){return this.state.musicbrainz.callsThisRun<this.state.musicbrainz.perRunCap;} async recordMusicbrainzAttempt(){const gap=Date.now()-this._lastMusicbrainzCallAt;if(gap<config.MUSICBRAINZ.minDelayMs)await sleep(config.MUSICBRAINZ.minDelayMs-gap);this._lastMusicbrainzCallAt=Date.now();this.state.musicbrainz.callsThisRun++;this.state.musicbrainz.lastCallAt=new Date().toISOString();}
  finishRun(summary){const d=ensureSpotifyDiagnostics(this.state);d.circuitFinish=this.state.spotify.circuit?{status:this.state.spotify.circuit.status||null,reason:this.state.spotify.circuit.reason||null}:null;this.state.lastRun={startedAt:this._startedAt||new Date().toISOString(),finishedAt:new Date().toISOString(),ticketmasterCalls:this.state.ticketmaster.callsThisRun,tavilyCalls:this.state.tavily.callsThisRun,groqCalls:this.state.groq.callsThisRun,groqTokens:this.state.groq.tokensThisRun,setlistfmCalls:this.state.setlistfm.callsThisRun,spotifyCalls:this.state.spotify.callsThisRun,musicbrainzCalls:this.state.musicbrainz.callsThisRun,spotifyDiagnostics:d,notes:this._notes,...summary};}
  finishMusicbrainzRun(summary){this.state.lastMusicbrainzRun={startedAt:this._startedAt||new Date().toISOString(),finishedAt:new Date().toISOString(),mode:'musicbrainz-only',musicbrainzCalls:this.state.musicbrainz.callsThisRun,identityUpdates:0,notes:this._notes,...summary};}
  finishProviderIdentityRun(summary){this.state.lastProviderIdentityRun={startedAt:this._startedAt||new Date().toISOString(),finishedAt:new Date().toISOString(),mode:'provider-identity-only',ticketmasterCalls:this.state.ticketmaster.callsThisRun,spotifyCalls:this.state.spotify.callsThisRun,notes:this._notes,...summary};}
  async save(){await worker.writeJson('apiUsage.json',this.state);}
}
module.exports={UsageTracker,freshState,safeCounter,ensureTavilyUsageState,ensureMusicbrainzState,ensureStructuredResearchState,ensureSpotifyDiagnostics};
